main_m – Smoke Ring
main_m Program
Akira Kageyama
2020.01.22
33 statements
Source File
Uses
constants_m
ut_m
params_m
debug_m
grid_m
field_m
slicedata_m
solver_m
job_m
渦輪 (smoke ring) の形成シミュレーション
神戸大学情報知能工学科の講義 "HPC" （B3対象）用サンプルコード
### 形状 直方体領域。3次元周期境界条件。カーテシアン座標。
### 計算手法 空間離散化は2次中心差分法。時間積分は4次ルンゲ・クッタ法。
### 実行方法 (1) cd src (2) make (3) cd ../slice_grapher (4) make
Calls
Contents
Variables
dt fluid nloop time
Source Code
main_m
Variables
Type Attributes Name Initial
real(kind=DR) :: dt
type(field__fluid_t) :: fluid
integer(kind=DI) :: nloop
real(kind=DR) :: time
Source Code
program main_m
  use constants_m  ! 定数
  use ut_m         ! ユーティリティ
  use params_m     ! パラメータ
  use debug_m      ! デバッグ
  use grid_m       ! 格子点情報
  use field_m      ! 流体場の構造体定義
  use slicedata_m  ! 可視化用断面データ出力
  use solver_m     ! ナビエ・ストークス方程式ソルバ
  use job_m        ! ジョブ管理
  implicit none    ! 暗黙の型宣言無効化。必須
  integer(DI) :: nloop ! シミュレーションのループカウンタ
  real(DR) :: dt, time ! 時間刻み幅と時刻
  type(field__fluid_t) :: fluid ! 流体場データの構造体
  call params__read
    ! パラメーターの読み込み。paramsの後に続くアンダースコア
    ! 二つは、これがparamsモジュールの中にあるサブルーチンの
    ! 呼び出しであることを意味している。paramsモジュールの
    ! 名前はparams_mである。params_mはparams.f90にある。
  call grid%initialize
    ! gridモジュールの初期化。
    ! パーセント記号はメンバアクセス演算子。
    ! ここでは構造体のメンバー関数の呼び出しをしている。
    ! gridモジュール（grid_m）はgrid.f90で定義されている。
  call solver__initialize(fluid)
    ! solverジュール（solver_m）の初期化。ここでは上の
    ! gridモジュールの場合と異なりメンバアクセス演算子
    ! （パーセント記号）を使っていない理由は特にない。
  call slicedata__initialize
    ! slicedataモジュールの初期化。
    ! このモジュールはシミュレーション領域の断面図を出力する。
  time = 0.0_DR  ! 時刻の初期化。単位は秒。
  nloop = 0      ! ループカウンタの初期化。
  call solver__diagnosis(nloop,time,fluid)
    ! solverモジュールで定義されているdiagnosis（診断）
    ! サブルーチンを呼び出す。医者が患者を診るのがdiagnosis
    ! である。そこでの診断結果はjobモジュールのjob__carte
    ! という構造体にセットする。carteはカルテである。
  dt = solver__set_time_step(nloop,fluid)
    ! 時間刻み幅 dt の決定。dtはCFL条件を満足するように決めるが、
    ! CFL条件は流体の状態に流体の状態に依存して変化する。
    ! たとえば、流体の一部が高温になると、そこでの音速が速くなり、
    ! 音速によって決まるCFL条件が厳しくなる（つまりdtが小さくなる）
    ! ここでは初期状態における流体の状態に基づいてdtが決まる
  do while(job__karte%state=="fine")
    ! このシミュレーションのメインループである。ジョブカルテが
    ! 「健康 (fine)」状態である限りシミュレーションを続行する。
    call debug__print("running. nloop=",nloop)
      ! このdebugモジュール中の標準出力書き出しルーチンの
      ! 呼び出し。通常のプリント文と異なりデバッグフラグがtrue
      ! の時だけメッセージを書き出すような仕組みにしている。
      ! デバッグフラグがfalseのときには何も書き出さない。
      ! デバッグフラグはparamsモジュール内で定義している。
    call solver__advance(time,dt,fluid)
      ! ナビエ・ストークス方程式に基づいて流体 (fluid) の状態を
      ! 一時刻ステップ dt だけ進める。
    dt = solver__set_time_step(nloop,fluid)
      ! 流体の状態が変わったのでCFL条件に基づき時間刻み幅dt
      ! を設定し直す。
      ! 厳密に言えば毎ステップこの再設定をしているわけではなく、
      ! このsolver__set_time_stepルーチンの冒頭で判断し、
      ! 数十ステップに一度だけ実際には変更を行うようなskip操作
      ! をしている。CFL条件に基づいた計算は時間がかかるが、
      ! 毎ステップdtを精密に調整する必要はないからである。
    nloop = nloop + 1  ! ループカウンタのインクリメント
    call solver__diagnosis(nloop,time,fluid)
      ! 診断。異常があればjob__carteにセットする。
    call slicedata__write(nloop,time,fluid)
      ! 断面データのディスクへの書き出し
    if (nloop>=params__get_integer('Total_nloop'))  &
      call job__karte%set("loop_max")
      ! あらかじめparamsモジュールで設定されたループカウンタの
      ! 上限値に達したらジョブを停止する。
  end do
  call job__finalize(nloop)
      ! ジョブの後始末。実際にはメーセージを標準出力に書くだけ。
end program main_m
Call graph
main_m calls slicedata__initialize, debug__print, slicedata__write, params__read, solver__initialize, job__finalize, solver__advance, solver__set_time_step, solver__diagnosis, params__get_integer
slicedata__initialize calls debug__print, params__get_string
debug__print calls print_str_dint, print_str_double, print_str, print_str_dint_double, print_str_sint, print_str_sint_double
slicedata__write calls debug__print, params__get_integer, solver__get_subfield, ut__message, ut__assert, make_single_precision_field
solver__initialize calls debug__print, params__get_double, set_drive_force_field
job__finalize calls ut__message
solver__advance calls debug__print, operator_fluid_add, subfield_vel_tm_divv, the_equation, operator_fluid_times_real
solver__set_time_step calls ut__message, params__get_logical, ut__assert, subfield_vel_tm
solver__diagnosis calls debug__print, ut__message, subfield_vel, operator_energyintegral, operator_scalarintegral
params__get_integer calls ut__message, ut__assert, ut__fatal
solver__get_subfield calls subfield_vel, subfield_vel_tm_divv, subfield_vel_tm
print_str_dint calls params__get_logical
ut__message calls message_str_double, message_str_dint_double, message_str_float, message_decorated_str_dint, message_decorated_str, message_str_sint, message_str, message_str_sint_double_double, message_str_dint, message_str_dint_double_double, message_str_sint_double, message_decorated_str_sint
subfield_vel calls debug__print, operator_vector_divby_scalar
print_str_double calls ut__message, params__get_logical
params__get_logical calls ut__message, ut__assert, ut__fatal
print_str calls ut__message, params__get_logical
print_str_dint_double calls params__get_logical
params__get_double calls ut__message, ut__assert, ut__fatal
subfield_vel_tm_divv calls debug__print, operator_div, operator_vector_divby_scalar
print_str_sint calls params__get_logical
the_equation calls debug__print, ut__assert, field__boundary_condition, drive_force_factor
ut__assert calls ut__fatal
set_drive_force_field calls debug__print, field__boundary_condition
print_str_sint_double calls params__get_logical
operator_energyintegral calls operator_dot_product
ut__fatal calls ut__message
params__get_string calls ut__message, ut__assert, ut__fatal
subfield_vel_tm calls debug__print, operator_vector_divby_scalar
make_single_precision_field calls debug__print, operator_curl, operator_dot_product
operator_curl calls boundary_condition_vector
operator_div calls boundary_condition_scalar
field__boundary_condition calls boundary_condition_scalar, boundary_condition_vector, boundary_condition_fluid
message_decorated_str_dint calls message_decorated_str
drive_force_factor calls ut__assert
message_decorated_str_sint calls message_decorated_str
boundary_condition_fluid calls boundary_condition_scalar, boundary_condition_vector