burgers_equation – Burgers Equation
burgers_equation Function
14 statements
Source File
private function burgers_equation(nx, dx, psi)
バーガーズ方程式の2階中心差分 境界点を除いた内側の格子点を更新する
Note
ここで更新していない境界上の格子点は、 境界条件で更新する必要がある。
Arguments
Type Intent Optional Attributes Name
integer(kind=SI), intent(in) :: nx
格子点数
real(kind=DR), intent(in) :: dx
格子間隔
real(kind=DR), intent(in), dimension(nx) :: psi
振幅（主変数）
Return Value real(kind=DR), dimension(nx)
積分後の配列を返す
Calls
Called by
Contents
Source Code
burgers_equation
Source Code
  function burgers_equation(nx,dx,psi)
    !! バーガーズ方程式の2階中心差分
    !! 境界点を除いた内側の格子点を更新する
    !! @note
    !!   ここで更新していない境界上の格子点は、
    !!   境界条件で更新する必要がある。
    integer(SI), intent(in) :: nx                !! 格子点数
    real(DR), intent(in) :: dx                   !! 格子間隔
    real(DR), dimension(nx), intent(in) :: psi   !! 振幅（主変数）
    real(DR), dimension(nx) :: burgers_equation  !! 積分後の配列を返す
    integer(SI) :: i
    real(DR) :: dx1  ! 一階差分演算子（定数）割り算削減のため定義
    real(DR) :: dx2  ! 二階差分演算子（定数）割り算削減のため定義
    dx1 = 1.0_DR / (2*dx)
    dx2 = namelist__get_double('Diffusion_coeff')/(dx**2)
    do i = 2 , nx-1
       burgers_equation(i) = - psi(i)*dx1*(psi(i+1)-psi(i-1)) &
                             + dx2*(psi(i+1)-2*psi(i)+psi(i-1))
    end do
  end function burgers_equation
Call graph
burgers_equation calls namelist__get_double
namelist__get_double calls ut__message, ut__fatal, ut__assert
ut__message calls message_str, message_decorated_str, message_str_double_double, message_decorated_str_dint, message_str_double, message_str_dint, message_str_sint_double, message_decorated_str_sint, message_str_dint_double, message_str_sint
ut__fatal calls ut__message
ut__assert calls ut__fatal
message_decorated_str_dint calls message_decorated_str
message_decorated_str_sint calls message_decorated_str
rk4__step calls burgers_equation
main calls rk4__step