iSave – Burgers Equation
iSave Subroutine
11 statements
Source File
subroutine iSave()
Arguments
None
Calls
Called by
Contents
Source Code
iSave
Source Code
  subroutine iSave
    integer(SI), save :: counter = 0
    integer(SI) :: i
    ! ディスクへの書き出し
    open(10,file="output.data" // '.' // ut__i2c3(counter))
      ! ファイルオープン
      ! スラッシュ記号2つ連続は文字列連結演算子
      ! ut__i2c3はutモジュールで定義された整数（i）を3文字
      ! に変換する関数
      do i = 1, nx
         write(10,*) xpos(i), psi(i)  ! gnuplotのフォーマット準拠
                                      ! つまりxの値とyの値を空白で区切る
      end do
    close(10)
    counter = counter + 1
    ! ファイル名に整数連番を不可する。その数字のインクリメント
    call ut__message(" Data saved at nloop, time = ", nloop, time)
    ! これも多重定義。文字列に整数、浮動小数点数をつなげて出力
  end subroutine iSave
Call graph
isave calls ut__i2c3, ut__message
ut__message calls message_str_double_double, message_str, message_decorated_str_dint, message_decorated_str_sint, message_str_double, message_decorated_str, message_str_sint, message_str_dint, message_str_dint_double, message_str_sint_double
message_decorated_str_dint calls message_decorated_str
message_decorated_str_sint calls message_decorated_str
main calls isave