message_str_dint – Burgers Equation
message_str_dint Subroutine
5 statements
Source File
private subroutine message_str_dint(string, int)
文字列 + 倍精度整数の出力
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
メーセージ文字列
integer(kind=DI), intent(in) :: int
書き出される整数
Called by
Contents
Source Code
message_str_dint
Source Code
  subroutine message_str_dint(string, int)
    !! 文字列 + 倍精度整数の出力
    character(len=*), intent(in) :: string  !! メーセージ文字列
    integer(DI), intent(in)      :: int     !! 書き出される整数
    write(6,*) string, int
  end subroutine message_str_dint
Call graph
ut__message calls message_str_dint
isave calls ut__message
ut__fatal calls ut__message
namelist__get_integer calls ut__message, ut__fatal, ut__assert
namelist__get_double calls ut__message, ut__fatal, ut__assert
main calls ut__message, isave, namelist__get_integer, namelist__get_double, rk4__step
burgers_equation calls namelist__get_double
ut__assert calls ut__fatal
rk4__step calls ut__fatal, burgers_equation