message_decorated_str_dint – Burgers Equation
message_decorated_str_dint Subroutine
8 statements
Source File
private subroutine message_decorated_str_dint(mark, string, int)
飾り文字でメーセージ文と倍精度整数を囲む
Usage:
call mess...('#','This is message at nloop = ', nloop)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: mark
この文字で全体を囲む
character(len=*), intent(in) :: string
メーセージ文字列
integer(kind=DI), intent(in) :: int
文字列の後に書く倍精度整数
Calls
Called by
Contents
Source Code
message_decorated_str_dint
Source Code
  subroutine message_decorated_str_dint(mark,string,int)
    !! 飾り文字でメーセージ文と倍精度整数を囲む
    !!
    !! Usage:
    !!
    !!    call mess...('#','This is message at nloop = ', nloop)
    !!
    character, intent(in)        :: mark   !! この文字で全体を囲む
    character(len=*), intent(in) :: string !! メーセージ文字列
    integer(DI), intent(in)      :: int    !! 文字列の後に書く倍精度整数
    character(len=200) :: string_int
    write(string_int,'(a,i16)') string, int
    call message_decorated_str(mark, string_int)
  end subroutine message_decorated_str_dint
Call graph
message_decorated_str_dint calls message_decorated_str
ut__message calls message_decorated_str_dint
main calls ut__message, isave, namelist__get_double, namelist__get_integer, rk4__step
isave calls ut__message
ut__fatal calls ut__message
namelist__get_double calls ut__message, ut__fatal, ut__assert
namelist__get_integer calls ut__message, ut__fatal, ut__assert
burgers_equation calls namelist__get_double
rk4__step calls ut__fatal, burgers_equation
ut__assert calls ut__fatal