message_str_sint_double – Burgers Equation
message_str_sint_double Subroutine
6 statements
Source File
private subroutine message_str_sint_double(string, i1, d1)
文字列 + 単精度整数 + 倍精度実数の出力
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
メーセージ文字列
integer(kind=SI), intent(in) :: i1
書き出される整数
real(kind=DR), intent(in) :: d1
書き出される実数
Called by
Contents
Source Code
message_str_sint_double
Source Code
  subroutine message_str_sint_double(string, i1, d1)
    !! 文字列 + 単精度整数 + 倍精度実数の出力
    character(len=*), intent(in) :: string  !! メーセージ文字列
    integer(SI), intent(in)      :: i1      !! 書き出される整数
    real(DR), intent(in)         :: d1      !! 書き出される実数
    write(6,*) string, i1, d1
  end subroutine message_str_sint_double
Call graph
ut__message calls message_str_sint_double
isave calls ut__message
namelist__get_integer calls ut__message, ut__fatal, ut__assert
ut__fatal calls ut__message
main calls ut__message, isave, namelist__get_integer, namelist__get_double, rk4__step
namelist__get_double calls ut__message, ut__fatal, ut__assert
rk4__step calls ut__fatal, burgers_equation
burgers_equation calls namelist__get_double
ut__assert calls ut__fatal