message_decorated_str – Burgers Equation
message_decorated_str Subroutine
9 statements
Source File
private subroutine message_decorated_str(mark, string)
飾り文字でメーセージ文を囲む
Usage:
  call message_decorated_str('#',"This is a test.")
Output:
  ###################
  # This is a test. #
  ###################
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: mark
この文字でメーセージを囲む
character(len=*), intent(in) :: string
出力メーセージ（文字列）
Called by
Contents
Source Code
message_decorated_str
Source Code
  subroutine message_decorated_str(mark,string)
    !! 飾り文字でメーセージ文を囲む
    !!
    !!   Usage:
    !!
    !!      call message_decorated_str('#',"This is a test.")
    !!
    !!   Output:
    !!
    !!      ###################
    !!      # This is a test. #
    !!      ###################
    !!
    character, intent(in)        :: mark    !! この文字でメーセージを囲む
    character(len=*), intent(in) :: string  !! 出力メーセージ（文字列）
    integer(SI) :: len
    len = len_trim(string) + 4
    write(6,*) repeat(mark,len)
    write(6,*) mark//' '//trim(string)//' '//mark
    write(6,*) repeat(mark,len)
  end subroutine message_decorated_str
Call graph
message_decorated_str_dint calls message_decorated_str
message_decorated_str_sint calls message_decorated_str
ut__message calls message_decorated_str, message_decorated_str_dint, message_decorated_str_sint
main calls ut__message, isave, namelist__get_double, namelist__get_integer, rk4__step
isave calls ut__message
ut__fatal calls ut__message
namelist__get_double calls ut__message, ut__fatal, ut__assert
namelist__get_integer calls ut__message, ut__fatal, ut__assert
burgers_equation calls namelist__get_double
rk4__step calls ut__fatal, burgers_equation
ut__assert calls ut__fatal