namelist__get_double – Burgers Equation
namelist__get_double Function
12 statements
Source File
public function namelist__get_double(variable)
このモジュールの外からの問い合わせに応じてnamelistデータを返す。 その変数が倍精度浮動小数点数の場合。 この関数の前にnamelist__readが呼ばれている必要がある。 この点はassertで確認している。
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: variable
問い合わせ変数
Return Value real(kind=DR)
保持データをそのまま返す
Calls
Called by
Contents
Source Code
namelist__get_double
Source Code
  function namelist__get_double(variable)
    !! このモジュールの外からの問い合わせに応じてnamelistデータを返す。
    !! その変数が倍精度浮動小数点数の場合。
    !! この関数の前にnamelist__readが呼ばれている必要がある。
    !! この点はassertで確認している。
    character(len=*), intent(in) :: variable !! 問い合わせ変数
    real(DR) :: namelist__get_double         !! 保持データをそのまま返す
    call ut__assert(Read_done,  &
                    '<namelist__get_double> Read namelist first.')
    select case (variable)
    case                ('Diffusion_coeff')
       namelist__get_double = Diffusion_coeff
    case default
       call ut__message('? arg = ', variable)
       call ut__fatal('<namelist__get_double> not in the namelist?')
    end select
  end function namelist__get_double
Call graph
namelist__get_double calls ut__message, ut__assert, ut__fatal
ut__message calls message_str_double_double, message_str, message_decorated_str_dint, message_decorated_str_sint, message_str_double, message_decorated_str, message_str_sint, message_str_dint, message_str_dint_double, message_str_sint_double
ut__assert calls ut__fatal
ut__fatal calls ut__message
message_decorated_str_dint calls message_decorated_str
message_decorated_str_sint calls message_decorated_str
burgers_equation calls namelist__get_double
main calls namelist__get_double, rk4__step
rk4__step calls burgers_equation