namelist__get_integer – Burgers Equation
namelist__get_integer Function
12 statements
Source File
public function namelist__get_integer(variable)
このモジュールの外からの問い合わせに応じてnamelistデータを返す。 その変数が整数の場合。 この関数の前にnamelist__readが呼ばれている必要がある。 この点はassertで確認している。
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: variable
Return Value integer(kind=SI)
Calls
Called by
Contents
Source Code
namelist__get_integer
Source Code
  function namelist__get_integer(variable)
    !! このモジュールの外からの問い合わせに応じてnamelistデータを返す。
    !! その変数が整数の場合。
    !! この関数の前にnamelist__readが呼ばれている必要がある。
    !! この点はassertで確認している。
    character(len=*), intent(in) :: variable
    integer(SI) :: namelist__get_integer
    call ut__assert(Read_done,  &
                    '<namelist__get_integer> Read namelist first.')
    select case (variable)
    case                 ('Nx')
       namelist__get_integer = Nx
    case default
       call ut__message('? arg = ', variable)
       call ut__fatal('<namelist__get_integer> not in the namelist?')
    end select
  end function namelist__get_integer
Call graph
namelist__get_integer calls ut__fatal, ut__assert, ut__message
ut__fatal calls ut__message
ut__assert calls ut__fatal
ut__message calls message_decorated_str, message_decorated_str_sint, message_str_sint, message_str_sint_double, message_decorated_str_dint, message_str_dint, message_str_dint_double, message_str, message_str_double, message_str_double_double
message_decorated_str_sint calls message_decorated_str
message_decorated_str_dint calls message_decorated_str
main calls namelist__get_integer