rk4__step – Burgers Equation
rk4__step Function
24 statements
Source File
public function rk4__step(nth, dt, dx, psi, dpsi_prev) result(dpsi_new)
4段4次のRunge-Kutta法による1ステップ積分の実行
Note
教科書のアルゴリズムをそのまま実装している。 メモリを贅沢に使っていることに注意。
Arguments
Type Intent Optional Attributes Name
character(len=3), intent(in) :: nth
4段の何番目か
real(kind=DR), intent(in) :: dt
積分時間刻み
real(kind=DR), intent(in) :: dx
格子間隔
real(kind=DR), intent(in), dimension(:) :: psi
被積分関数
real(kind=DR), intent(in), optional dimension(size(psi,dim=1)) :: dpsi_prev
前段の増分
Return Value real(kind=DR), dimension(size(psi,dim=1))
現段の増分 配列で返す
Calls
Called by
Contents
Source Code
rk4__step
Source Code
  function rk4__step(nth,dt,dx,psi,dpsi_prev) result(dpsi_new)
    !! 4段4次のRunge-Kutta法による1ステップ積分の実行
    !! @note 教科書のアルゴリズムをそのまま実装している。
    !!       メモリを贅沢に使っていることに注意。
    character(len=3), intent(in) :: nth       !! 4段の何番目か
    real(DR), intent(in) :: dt                !! 積分時間刻み
    real(DR), intent(in) :: dx                !! 格子間隔
    real(DR), dimension(:), intent(in) :: psi !! 被積分関数
    real(DR), dimension(size(psi,dim=1)), intent(in), optional :: dpsi_prev
                                              !! 前段の増分
    real(DR), dimension(size(psi,dim=1)) :: dpsi_new
                                              !! 現段の増分
                                              !! 配列で返す
    real(DR), dimension(size(psi,dim=1)) :: psi_   ! 作業配列
    ! 古典的な4段4次のRunge-Kutta積分法
    select case (nth)
    case ('1st') ! 第1段
       dpsi_new(:) = dt*burgers_equation(size(psi,dim=1),dx,psi)
    case ('2nd') ! 第2段
       psi_(:) = psi(:) + dpsi_prev(:)*0.5_DR
       dpsi_new(:) = dt*burgers_equation(size(psi,dim=1),dx,psi_)
    case ('3rd') ! 第3段
       psi_(:) = psi(:) + dpsi_prev(:)*0.5_DR
       dpsi_new(:) = dt*burgers_equation(size(psi,dim=1),dx,psi_)
    case ('4th') ! 第4段
       psi_(:) = psi(:) + dpsi_prev(:)
       dpsi_new(:) = dt*burgers_equation(size(psi,dim=1),dx,psi_)
    case default
       call ut__fatal('<rk4> Invalid step.')
    end select
  end function rk4__step
Call graph
rk4__step calls ut__fatal, burgers_equation
ut__fatal calls ut__message
burgers_equation calls namelist__get_double
namelist__get_double calls ut__fatal, ut__message, ut__assert
ut__message calls message_decorated_str, message_decorated_str_sint, message_str_sint, message_decorated_str_dint, message_str_sint_double, message_str_dint, message_str_dint_double, message_str, message_str_double, message_str_double_double
message_decorated_str_sint calls message_decorated_str
message_decorated_str_dint calls message_decorated_str
ut__assert calls ut__fatal
main calls rk4__step