#!/bin/sh
#-------------------------------------------------------------------
# class-hpc-smoke-ring: A simple sample field solver.
#
#    by Akira Kageyama, Kobe University, Japan.
#       email: sgks@mac.com
#
#    Copyright 2018 Akira Kageyama
#
#    This software is released under the MIT License.
#
#-------------------------------------------------------------------
#    warming_up/burgers_equation/generate-plot-script.sh
#-------------------------------------------------------------------


filebase="output.data"

echo '# gnuplot script generated by generate-plot-script.sh.'
echo '# '
echo ' '
echo "set xrange [-pi : pi]"
echo 'set yrange [0 : 1.2]'
echo ' '

maxfilenum=`ls -1 $filebase.??? | tail -1 | rev | cut -d. -f1 | rev`

echo "do for [i=0:$maxfilenum] {"
echo "  num = sprintf("%03d", i)"
echo "  filename = sprintf("output.data.%03d", i)"
echo "  plot filename w lp t num"
echo "  if (i==0) {"
echo "    pause 4.9"
echo "  }"
echo "  pause 0.1"
echo "}"
echo "pause -1"
