#!/bin/sh
#-------------------------------------------------------------------
# class-hpc-smoke-ring: A simple sample field solver.
#
#    by Akira Kageyama, Kobe University, Japan.
#       email: sgks@mac.com
#
#    Copyright 2018 Akira Kageyama
#
#    This software is released under the MIT License.
#
#-------------------------------------------------------------------
#    warming_up/burgers_equation/generate-plot-script.sh
#-------------------------------------------------------------------

pi="3.14159265"

filebase="output.data"

echo '# gnuplot script generated by generate-plot-script.sh.'
echo '# '
echo ' '
echo "set xrange [-${pi} : ${pi}]"
echo 'set yrange [0 : 1.2]'
echo ' '

pausetime_in_the_beginning="5"  # wait for this seconds.
pausetime_later="0.1"
pausetime=${pausetime_in_the_beginning}
for i in `ls $filebase.???`
do
  echo plot \'$i\' w lp
  echo pause ${pausetime}
  pausetime=${pausetime_later}
done
echo pause -1
