boundary_condition_scalar – Smoke Ring
boundary_condition_scalar Subroutine
9 statements
Source File
private subroutine boundary_condition_scalar(scalar)
スカラー場の境界条件設定
Arguments
Type Intent Optional Attributes Name
real(kind=DR), intent(inout), dimension(NX,NY,NZ) :: scalar
スカラー場
Called by
Contents
Source Code
boundary_condition_scalar
Source Code
  subroutine boundary_condition_scalar(scalar)
    !! スカラー場の境界条件設定
    real(DR), dimension(NX,NY,NZ), intent(inout) :: scalar !! スカラー場
    scalar( 1,:,:) = scalar(NX-1,:,:)
    scalar(NX,:,:) = scalar(   2,:,:)
    scalar(:, 1,:) = scalar(:,NY-1,:)
    scalar(:,NY,:) = scalar(:,   2,:)
    scalar(:,:, 1) = scalar(:,:,NZ-1)
    scalar(:,:,NZ) = scalar(:,:,   2)
  end subroutine boundary_condition_scalar
Call graph
operator_div calls boundary_condition_scalar
field__boundary_condition calls boundary_condition_scalar, boundary_condition_fluid
operator_laplacian_scalar calls boundary_condition_scalar
boundary_condition_fluid calls boundary_condition_scalar
the_equation calls field__boundary_condition
subfield_vel_tm_divv calls operator_div
set_drive_force_field calls field__boundary_condition
solver__advance calls the_equation, subfield_vel_tm_divv
solver__initialize calls set_drive_force_field
solver__get_subfield calls subfield_vel_tm_divv
main_m calls solver__advance, solver__initialize, slicedata__write
slicedata__write calls solver__get_subfield