boundary_condition_vector – Smoke Ring
boundary_condition_vector Subroutine
21 statements
Source File
private subroutine boundary_condition_vector(vec)
ベクトル場の境界条件設定
Arguments
Type Intent Optional Attributes Name
type(field__vector3d_t), intent(inout) :: vec
ベクトル場
Called by
Contents
Source Code
boundary_condition_vector
Source Code
  subroutine boundary_condition_vector(vec)
    !! ベクトル場の境界条件設定
    type(field__vector3d_t), intent(inout) :: vec !! ベクトル場
    vec%x( 1,:,:) = vec%x(NX-1,:,:)    !-- yz-plane --!
    vec%y( 1,:,:) = vec%y(NX-1,:,:)
    vec%z( 1,:,:) = vec%z(NX-1,:,:)
    vec%x(NX,:,:) = vec%x(   2,:,:)
    vec%y(NX,:,:) = vec%y(   2,:,:)
    vec%z(NX,:,:) = vec%z(   2,:,:)
    vec%x(:, 1,:) = vec%x(:,NY-1,:)    !-- zx-plane --!
    vec%y(:, 1,:) = vec%y(:,NY-1,:)
    vec%z(:, 1,:) = vec%z(:,NY-1,:)
    vec%x(:,NY,:) = vec%x(:,   2,:)
    vec%y(:,NY,:) = vec%y(:,   2,:)
    vec%z(:,NY,:) = vec%z(:,   2,:)
    vec%x(:,:, 1) = vec%x(:,:,NZ-1)    !-- xy-plane --!
    vec%y(:,:, 1) = vec%y(:,:,NZ-1)
    vec%z(:,:, 1) = vec%z(:,:,NZ-1)
    vec%x(:,:,NZ) = vec%x(:,:,   2)
    vec%y(:,:,NZ) = vec%y(:,:,   2)
    vec%z(:,:,NZ) = vec%z(:,:,   2)
  end subroutine boundary_condition_vector
Call graph
operator_curl calls boundary_condition_vector
operator_laplacian_vector calls boundary_condition_vector
field__boundary_condition calls boundary_condition_vector, boundary_condition_fluid
boundary_condition_fluid calls boundary_condition_vector
the_equation calls field__boundary_condition
make_single_precision_field calls operator_curl
set_drive_force_field calls field__boundary_condition
solver__advance calls the_equation
solver__initialize calls set_drive_force_field
slicedata__write calls make_single_precision_field
main_m calls solver__advance, solver__initialize, slicedata__write