boundary_condition_fluid – Smoke Ring
boundary_condition_fluid Subroutine
6 statements
Source File
private subroutine boundary_condition_fluid(fluid)
流体構造体の境界条件設定
Arguments
Type Intent Optional Attributes Name
type(field__fluid_t), intent(inout) :: fluid
流体場
Calls
Called by
Contents
Source Code
boundary_condition_fluid
Source Code
  subroutine boundary_condition_fluid(fluid)
    !! 流体構造体の境界条件設定
    type(field__fluid_t), intent(inout) :: fluid !! 流体場
    call boundary_condition_scalar(fluid%pressure)
    call boundary_condition_scalar(fluid%density)
    call boundary_condition_vector(fluid%flux)
  end subroutine boundary_condition_fluid
Call graph
boundary_condition_fluid calls boundary_condition_scalar, boundary_condition_vector
field__boundary_condition calls boundary_condition_fluid
the_equation calls field__boundary_condition
set_drive_force_field calls field__boundary_condition
solver__advance calls the_equation
solver__initialize calls set_drive_force_field
main_m calls solver__advance, solver__initialize