draw_arrows – Smoke Ring
draw_arrows Subroutine
44 statements
Source File
private subroutine draw_arrows(ll, ur, filename, vector)
Arguments
Type Intent Optional Attributes Name
type(vv_sketch__sim_pos_t), intent(in) :: ll
type(vv_sketch__sim_pos_t), intent(in) :: ur
character(len=*), intent(in) :: filename
type(vv_slice_vector_t), intent(inout) :: vector
Calls
Contents
Source Code
draw_arrows
Source Code
  subroutine draw_arrows( ll, ur, filename, vector )
    type(vv_sketch__sim_pos_t), intent(in) :: ll,  &  ! lower left
                                       ur      ! upper right
    character(len=*), intent(in) :: filename
    type(vv_slice_vector_t), intent(inout) :: vector
    real :: vec_amp_max
    type(vv_sketch_t) :: vv_sketch
    type(vv_color_t) :: color_black
    type(vv_color_t) :: color_limegreen, color_darkgreen
    character(len=TAG_NAME_MAX) :: message
    real, parameter :: ALMOST_ZERO = 1.e-20_SR
    color_black   = VV_COLOR__CONST%black
    color_limegreen = VV_COLOR__CONST%limegreen
    color_darkgreen = VV_COLOR__CONST%darkgreen
    call vv_sketch%initialize( ll, ur, &
                               screen_width_in_pixel=1000.0, &
                               title=vector%tag,             &
                               filename=trim(filename),      &
                               unit_arrow_in_pixel=20.0,     &
                               write_arrow_template=.true. )
    ! --<boundary curve>--
    call vector%mesh%draw( vv_sketch, &
                           line_color=VV_COLOR__CONST%black,  &
                           width_in_pixels=1.0 )
    vec_amp_max = sqrt(maxval(vector%comp_u(:,:)**2  &
                            + vector%comp_v(:,:)**2))
    message = vec_amp_max_string( vec_amp_max )
    call iText_in_header_and_footer( message )
    if ( vec_amp_max <= ALMOST_ZERO ) then
      call vv_sketch%finalize
      return
    end if
    call vv_sketch%group_push( line_color=color_limegreen,  &
                               fill_color=color_darkgreen,  &
                               line_width_in_pixel=1.0 )
      vector%comp_u(:,:) = vector%comp_u(:,:) / vec_amp_max
      vector%comp_v(:,:) = vector%comp_v(:,:) / vec_amp_max
      call vector%vis_arrows( vv_sketch, arrow_template="#arrow02" )
    call vv_sketch%group_pop
    call vv_sketch%finalize
  contains
    subroutine iText_in_header_and_footer( message )
      character(len=TAG_NAME_MAX), intent(in) :: message
      real :: text_v_pos_in_physical_unit
      real :: tsep ! text v position separation betwen lines
      call vv_sketch%group_push( line_color=color_black,  &
                                 line_width_in_pixel=1.0 )
      tsep = (ur%v-ll%v)*0.1
      ! --<figure title in the header>--
      text_v_pos_in_physical_unit = ur%v + tsep
      call vv_sketch%text( (ll%u+ur%u)/2,  &
                           text_v_pos_in_physical_unit,  &
                           vv_sketch%title,  &
                           font_size_in_pixel=30.0,  &
                           text_anchor='middle' )
      ! --<simple text in the footer>--
      text_v_pos_in_physical_unit = ll%v - tsep
      call vv_sketch%text( ll%u,  &
                           text_v_pos_in_physical_unit,  &
                           trim(filename),  &
                           font_size_in_pixel=15.0,  &
                           text_anchor='start' )
      text_v_pos_in_physical_unit = text_v_pos_in_physical_unit - tsep
      call vv_sketch%text( ll%u,  &
                           text_v_pos_in_physical_unit,  &
                           message,  &
                           font_size_in_pixel=15.0,  &
                           text_anchor='start' )
      call vv_sketch%group_pop
    end subroutine iText_in_header_and_footer
  end subroutine draw_arrows
Call graph
draw_arrows calls comp_u, comp_v, finalize, group_pop, group_push, initialize, vec_amp_max_string, vis_arrows
vec_amp_max_string calls ut__real_to_str10