draw_contour_and_arrows – Smoke Ring
draw_contour_and_arrows Subroutine
72 statements
Source File
private subroutine draw_contour_and_arrows(ll, ur, filename, scalar, vector)
<
<
Arguments
Type Intent Optional Attributes Name
type(vv_sketch__sim_pos_t), intent(in) :: ll
type(vv_sketch__sim_pos_t), intent(in) :: ur
character(len=*), intent(in) :: filename
type(vv_slice_scalar_t), intent(inout) :: scalar
type(vv_slice_vector_t), intent(inout) :: vector
Calls
Called by
Contents
Source Code
draw_contour_and_arrows
Source Code
  subroutine draw_contour_and_arrows( ll, ur, filename, scalar, vector )
    type(vv_sketch__sim_pos_t), intent(in) :: ll,  &  ! lower left
                                       ur      ! upper right
    character(len=*), intent(in) :: filename
    type(vv_slice_scalar_t), intent(inout) :: scalar
    type(vv_slice_vector_t), intent(inout) :: vector
    real :: vec_amp_max
    type(vv_sketch_t) :: vv_sketch
    real :: level_min, level_max, dlevel, level, level_nrm
    real :: max_min_diff_normalized
    real :: level_range
    real :: level_amplitude
    type(vv_color_t) :: color, color_black
    type(vv_color_t) :: color_brown, color_sandybrown
    integer :: l
    character(len=TAG_NAME_MAX) :: message1, message2
    character(len=TAG_NAME_MAX*2) :: figure_title
    real, parameter :: ALMOST_ZERO = 1.e-20_SR
    real, parameter :: TOO_SMALL_DIFF_FOR_CONTOUR = 1.e-3_SR
    color_black       = VV_COLOR__CONST%black
    color_brown = VV_COLOR__CONST%brown
    color_sandybrown  = VV_COLOR__CONST%sandybrown
    figure_title = trim(scalar%tag) // ' (contour) and ' // &
                   trim(vector%tag) // ' (arrows)'
    call vv_sketch%initialize( ll, ur,  &
                               screen_width_in_pixel=1000.0, &
                               title=figure_title,           &
                               filename=trim(filename),      &
                               unit_arrow_in_pixel=20.0,     &
                               write_arrow_template=.true. )
    ! --<boundary curve>--
    call scalar%mesh%draw( vv_sketch, &
                           line_color=VV_COLOR__CONST%black,  &
                           width_in_pixels=1.0 )
    level_min = minval(scalar%val_vert)
    level_max = maxval(scalar%val_vert)
    message1 = min_max_string( level_min, level_max )
    vec_amp_max = sqrt(maxval(vector%comp_u(:,:)**2  &
                            + vector%comp_v(:,:)**2))
    message2 = vec_amp_max_string( vec_amp_max )
    call iText_in_header_and_footer( message1, message2 )
    !!>
!        Contours
    !!<
    level_amplitude = max(abs(level_max),abs(level_min))
    if ( level_amplitude > ALMOST_ZERO ) then
      call vv_sketch%group_push( line_color=color_black,  &
                                 line_width_in_pixel=1.0 )
        level_range = level_max - level_min
        max_min_diff_normalized = level_range / level_amplitude
        if ( max_min_diff_normalized >= TOO_SMALL_DIFF_FOR_CONTOUR )  then
          dlevel = level_range / 10
          do l = 1, 10
            level = level_min + dlevel*(real(l)-0.5)
            level_nrm = (level-level_min) / level_range
            color = vv_color__normalized_real_to_color( level_nrm )
            call scalar%vis_contour( vv_sketch,              &
                                     level,                  &
                                     line_color=color_black, &
                                     fill_color=color )
          end do
        end if
      call vv_sketch%group_pop
    end if
    !!>
!        Arrows
    !!<
    if ( vec_amp_max > ALMOST_ZERO ) then
      call vv_sketch%group_push( line_color=color_brown,  &
                                 fill_color=color_sandybrown, &
                                 line_width_in_pixel=1.0 )
          vector%comp_u(:,:) = vector%comp_u(:,:) / vec_amp_max
          vector%comp_v(:,:) = vector%comp_v(:,:) / vec_amp_max
          call vector%vis_arrows( vv_sketch, arrow_template="#arrow02" )
      call vv_sketch%group_pop
    end if
    call vv_sketch%finalize
  contains
    subroutine iText_in_header_and_footer( message1, message2 )
      character(len=TAG_NAME_MAX), intent(in) :: message1, message2
      real :: text_v_pos_in_physical_unit
      real :: tsep ! text v position separation betwen lines
      call vv_sketch%group_push( line_color=color_black,  &
                                 line_width_in_pixel=1.0 )
      tsep = (ur%v-ll%v)*0.1
      ! --<figure title in the header>--
      text_v_pos_in_physical_unit = ur%v + tsep
      call vv_sketch%text( (ll%u+ur%u)/2,                &
                           text_v_pos_in_physical_unit,  &
                           vv_sketch%title,              &
                           font_size_in_pixel=30.0,      &
                           text_anchor='middle' )
      ! --<simple text in the footer>--
      text_v_pos_in_physical_unit = ll%v - tsep
      call vv_sketch%text( ll%u,                         &
                           text_v_pos_in_physical_unit,  &
                           trim(filename),               &
                           font_size_in_pixel=15.0,      &
                           text_anchor='start' )
      text_v_pos_in_physical_unit = text_v_pos_in_physical_unit - tsep
      call vv_sketch%text( ll%u,                           &
                           text_v_pos_in_physical_unit,    &
                           'Contour: ' // trim(message1),  &
                           font_size_in_pixel=15.0,        &
                           text_anchor='start' )
      text_v_pos_in_physical_unit = text_v_pos_in_physical_unit - tsep
      call vv_sketch%text( ll%u,                         &
                           text_v_pos_in_physical_unit,  &
                           'Arrow: ' // trim(message2),  &
                           font_size_in_pixel=15.0,      &
                           text_anchor='start' )
      call vv_sketch%group_pop
    end subroutine iText_in_header_and_footer
  end subroutine draw_contour_and_arrows
Call graph
draw_contour_and_arrows calls comp_u, comp_v, finalize, group_pop, group_push, initialize, min_max_string, vec_amp_max_string, vis_arrows, vis_contour, vv_color__normalized_real_to_color
min_max_string calls ut__real_to_str10
vec_amp_max_string calls ut__real_to_str10
vis2d_plane_xy__draw calls draw_contour_and_arrows
vis2d_plane_xz__draw calls draw_contour_and_arrows