draw_contour – Smoke Ring
draw_contour Subroutine
60 statements
Source File
private subroutine draw_contour(ll, ur, filename, scalar)
default
Arguments
Type Intent Optional Attributes Name
type(vv_sketch__sim_pos_t), intent(in) :: ll
type(vv_sketch__sim_pos_t), intent(in) :: ur
character(len=*), intent(in) :: filename
type(vv_slice_scalar_t), intent(inout) :: scalar
Calls
Called by
Contents
Source Code
draw_contour
Source Code
  subroutine draw_contour( ll, ur, filename, scalar )
    type(vv_sketch__sim_pos_t), intent(in) :: ll,  &  ! lower left
                                       ur      ! upper right
    character(len=*), intent(in) :: filename
    type(vv_slice_scalar_t), intent(inout) :: scalar
    type(vv_sketch_t) :: vv_sketch
    real :: level_min, level_max, dlevel, level, level_nrm
    real :: level_range
    type(vv_color_t) :: color, color_black
    integer :: l
    character(len=TAG_NAME_MAX) :: message
    real, parameter :: ALMOST_ZERO = 1.e-20_SR
    real, parameter :: TOO_SMALL_DIFF_FOR_CONTOUR = 1.e-3_SR
    real :: max_min_diff_normalized
    real :: level_amplitude
    logical :: flag_skip_contour
    color_black   = VV_COLOR__CONST%black
    flag_skip_contour = .false. !! default
    call vv_sketch%initialize( ll, ur, &
                               screen_width_in_pixel=1000.0,  &
                               title=scalar%tag,              &
                               filename=trim(filename) )
    ! --<boundary curve>--
    call scalar%mesh%draw( vv_sketch, &
                           line_color=VV_COLOR__CONST%black,  &
                           width_in_pixels=1.0 )
    level_min = minval(scalar%val_vert)
    level_max = maxval(scalar%val_vert)
    message = min_max_string( level_min, level_max )
    call iText_in_header_and_footer( message )
    level_amplitude = max(abs(level_max),abs(level_min))
    if ( level_amplitude <= ALMOST_ZERO ) then
      call vv_sketch%finalize
      return
    end if
    level_range = level_max - level_min
    max_min_diff_normalized = level_range / level_amplitude
    if ( max_min_diff_normalized <= TOO_SMALL_DIFF_FOR_CONTOUR )  then
      call vv_sketch%finalize
      return
    end if
    call vv_sketch%group_push( line_color=VV_COLOR__CONST%magenta,  &
                               line_width_in_pixel=1.0 )
      dlevel = level_range / 10
      do l = 1, 10
        level = level_min + dlevel*(real(l)-0.5)
        level_nrm = (level-level_min) / level_range
        color = vv_color__normalized_real_to_color( level_nrm )
        call scalar%vis_contour( vv_sketch,              &
                                 level,                  &
                                 line_color=color_black, &
                                 fill_color=color )
                               ! debug_print=.true. ) ! for debug.
      end do
    call vv_sketch%group_pop
    call vv_sketch%finalize
  contains
    subroutine iText_in_header_and_footer( message )
      character(len=TAG_NAME_MAX), intent(in) :: message
      real :: text_v_pos_in_physical_unit
      real :: tsep ! text v position separation betwen lines
      call vv_sketch%group_push( line_color=color_black,  &
                                 line_width_in_pixel=1.0 )
      tsep = (ur%v-ll%v)*0.1
      ! --<figure title in the header>--
      text_v_pos_in_physical_unit = ur%v + tsep
      call vv_sketch%text( (ll%u+ur%u)/2,  &
                           text_v_pos_in_physical_unit,  &
                           vv_sketch%title,  &
                           font_size_in_pixel=30.0,  &
                           text_anchor='middle' )
      ! --<simple text in the footer>--
      text_v_pos_in_physical_unit = ll%v - tsep
      call vv_sketch%text( ll%u,  &
                           text_v_pos_in_physical_unit,  &
                           trim(filename),  &
                           font_size_in_pixel=15.0,  &
                           text_anchor='start' )
      text_v_pos_in_physical_unit = text_v_pos_in_physical_unit - tsep
      call vv_sketch%text( ll%u,  &
                           text_v_pos_in_physical_unit,    &
                           message,  &
                           font_size_in_pixel=15.0,  &
                           text_anchor='start' )
      call vv_sketch%group_pop
    end subroutine iText_in_header_and_footer
  end subroutine draw_contour
Call graph
draw_contour calls finalize, group_pop, group_push, initialize, min_max_string, vis_contour, vv_color__normalized_real_to_color
min_max_string calls ut__real_to_str10
vis2d_plane_xz__draw calls draw_contour