drive_force_factor – Smoke Ring
drive_force_factor Function
23 statements
Source File
private function drive_force_factor(time)
渦輪を駆動する力の時間変化の調整のための係数設定
Note
この係数は0以上1以下。これはassertで確認している。
Arguments
Type Intent Optional Attributes Name
real(kind=DR), intent(in) :: time
シミュレーション時刻
Return Value real(kind=DR)
力の強さ係数 0から1
Calls
Called by
Contents
Source Code
drive_force_factor
Source Code
  function drive_force_factor(time)
    !! 渦輪を駆動する力の時間変化の調整のための係数設定
    !!
    !! @note この係数は0以上1以下。これはassertで確認している。
    !!
    real(DR), intent(in) :: time !! シミュレーション時刻
    real(DR)             :: drive_force_factor  !! 力の強さ係数 0から1
    !
    !                                      factor
    !              ___________               |
    !             /|         |\              |
    !      ______/ |         | \______       +--------> time
    !            | |         |  |
    !            | |         |  |
    !            | t0        t1 |
    !          t_start         t_end
    !
    real(DR), parameter :: T_START =  0.0_DR  ! 力をかけ始める時刻
    real(DR), parameter :: T_END   =  0.01_DR ! 力をかけ終わる時刻
                                              ! 試行錯誤で調整せよ
    real(DR), parameter :: T0 = T_START + (T_END-T_START)/4
    real(DR), parameter :: T1 = T_END   - (T_END-T_START)/4
                                              ! 上のコメント図をみよ
                                              ! これも試行錯誤で調整せよ
    real(DR), parameter :: ONE  = 1.0_DR  ! コードの読みやすさのため定義
    real(DR), parameter :: ZERO = 0.0_DR  ! コードの読みやすさのため定義
    call ut__assert( T_START < T0 .and. T0 < T1 .and. T1 < T_END,  &
                    "<solver/drive_force_factor> Time inconsistent.")
      ! この関係は以下の前提なのでアサートで確認しておく
    ! 上のコメント図の時間依存係数
    if ( time <= T_START ) then
      drive_force_factor = ZERO
    else if ( time <= T0 ) then
      drive_force_factor = (time-T_START) / (T0-T_START)
    else if ( time <= T1 ) then
      drive_force_factor = ONE
    else if ( time <= T_END ) then
      drive_force_factor = ONE - (time-T1) / (T_END-T1)
    else
      drive_force_factor = ZERO
    end if
    call ut__assert(drive_force_factor >=0.0_DR  &
                              .and.  &
                    drive_force_factor <=1.0_DR,  &
                    "<solver/drive_force_factor> strange value.")
  end function drive_force_factor
Call graph
drive_force_factor calls ut__assert
ut__assert calls ut__fatal
ut__fatal calls ut__message
ut__message calls message_str_double, message_str_dint_double, message_str_float, message_decorated_str_dint, message_decorated_str, message_str_sint, message_str, message_str_sint_double_double, message_str_dint, message_str_dint_double_double, message_str_sint_double, message_decorated_str_sint
message_decorated_str_dint calls message_decorated_str
message_decorated_str_sint calls message_decorated_str
the_equation calls drive_force_factor
solver__advance calls the_equation
main_m calls solver__advance