initialize_pos – Smoke Ring
initialize_pos Function
15 statements
Source File
private function initialize_pos(gijk, pos_by_gijk) result(pos)
Arguments
Type Intent Optional Attributes Name
type(grid_global_ijk_t), intent(in) :: gijk
type(grid_pos_by_global_ijk_t), intent(in) :: pos_by_gijk
Return Value type(grid__pos_t)
Calls
Called by
Contents
Source Code
initialize_pos
Source Code
  function initialize_pos( gijk, pos_by_gijk ) result(pos)
    type(grid_global_ijk_t), intent(in) :: gijk
    type(grid_pos_by_global_ijk_t), intent(in) :: pos_by_gijk
    type(grid__pos_t) :: pos
    integer :: i, j, k
    do i = 0, NXPP1
      pos%x(i) = pos_by_gijk%x( gijk%gi(i) )
    end do
    do j = 0, NYPP1
      pos%y(j) = pos_by_gijk%y( gijk%gj(j) )
    end do
    do k = 0, NZPP1
      pos%z(k) = pos_by_gijk%z( gijk%gk(k) )
    end do
  end function initialize_pos
Call graph
initialize_pos calls x, y, z
grid__initialize calls initialize_pos