job__karte_set – Smoke Ring
job__karte_set Subroutine
18 statements
Source File
private subroutine job__karte_set(self, state_)
ジョブカルテの設定終了時の後始末。実際には健康状態カルテに応じた
構造体のメンバー関数としてcallするときその 構造体変数そのものがselfとして自動的に引数にはいる。 ここでの変数名はselfという名前でなくても構わない。
Arguments
Type Intent Optional Attributes Name
class(job__karte_t), intent(out) :: self
ジョブカルテ
character(len=*), intent(in) :: state_
設定する状態
Calls
Contents
Source Code
job__karte_set
Source Code
  subroutine job__karte_set(self, state_)
    !! ジョブカルテの設定終了時の後始末。実際には健康状態カルテに応じた
    !!
    !! 構造体のメンバー関数としてcallするときその
    !! 構造体変数そのものがselfとして自動的に引数にはいる。
    !! ここでの変数名はselfという名前でなくても構わない。
    class(job__karte_t), intent(out) :: self   !! ジョブカルテ
    character(len=*),    intent(in)  :: state_ !! 設定する状態
    select case (trim(state_))
      case ("fine")              ! 問題なく計算が進行している
        self%state = "fine"
      case ("time_out")          ! ジョブの時間切れ
        self%state = "time_out"
      case ("loop_max")          ! 設定されたループカウンタの最大値に到達した
        self%state = "loop_max"
      case ("over_flow")         ! 計算途中にオーバーフローが発生した
        self%state = "over_flow"
      case ("negative_anormaly") ! 密度など正でなければいけない量が負になった
        self%state = "negative_anormaly"
      case default               ! そんなstateは想定していない
        call ut__fatal("<job__karte_set> case error.")
    end select
  end subroutine job__karte_set
Call graph
job__karte_set calls ut__fatal
ut__fatal calls ut__message
ut__message calls message_str_double, message_str_dint_double, message_str_float, message_decorated_str_dint, message_decorated_str, message_str_sint, message_str, message_str_sint_double_double, message_str_dint, message_str_dint_double_double, message_str_sint_double, message_decorated_str_sint
message_decorated_str_dint calls message_decorated_str
message_decorated_str_sint calls message_decorated_str