job__finalize – Smoke Ring
job__finalize Subroutine
15 statements
Source File
public subroutine job__finalize(nloop)
ジョブ終了時の後始末。実際には健康状態カルテに応じた メッセージを標準出力に書くだけ
MPI化した場合、MPI_Finalizeをおくのはここがいいだろう。
ut__messageの第一引数と第二引数はどちらも文字（列） 変数であるが、第一引数はシングルクォーテーションマーク、 第二引数はダブルクオーテーションマークで囲っている。これは コンパイラにとっては無意味。Fortranでは2つのクォーテーション マークは区別しない。
Arguments
Type Intent Optional Attributes Name
integer(kind=DI), intent(in) :: nloop
ループカウンタ
Calls
Called by
Contents
Source Code
job__finalize
Source Code
  subroutine job__finalize(nloop)
    !! ジョブ終了時の後始末。実際には健康状態カルテに応じた
    !! メッセージを標準出力に書くだけ
    !!
    !! MPI化した場合、MPI_Finalizeをおくのはここがいいだろう。
    !!
    !! ut__messageの第一引数と第二引数はどちらも文字（列）
    !! 変数であるが、第一引数はシングルクォーテーションマーク、
    !! 第二引数はダブルクオーテーションマークで囲っている。これは
    !! コンパイラにとっては無意味。Fortranでは2つのクォーテーション
    !! マークは区別しない。
    integer(DI), intent(in) :: nloop !! ループカウンタ
    select case (trim(job__karte%state))
      case ("fine", "loop_max")
        call ut__message('#',"Successfully finished.") ! #で第2引数を囲む。
      case ("time_out")
        call ut__message('-',"Time out at nloop = ", nloop)
      case ("over_flow")
        call ut__message('%',"Overflow at nloop = ", nloop)
      case ("negative_anormaly")
        call ut__message('%',"Underflow at nloop = ",nloop)
      case default
        call ut__message('?',"Stopped at nloop = ",  nloop)
    end select
  end subroutine job__finalize
Call graph
job__finalize calls ut__message
ut__message calls message_str_double, message_str_dint_double, message_str_float, message_decorated_str_dint, message_decorated_str, message_str_sint, message_str, message_str_sint_double_double, message_str_dint, message_str_dint_double_double, message_str_sint_double, message_decorated_str_sint
message_decorated_str_dint calls message_decorated_str
message_decorated_str_sint calls message_decorated_str
main_m calls job__finalize