make_single_precision_field – Smoke Ring
make_single_precision_field Subroutine
15 statements
Source File
private subroutine make_single_precision_field(vel, ps)
シミュレーションで計算した速度場と圧力場 のx-z平面での断面データを求める。 その際、倍精度実数から単精度実数に型変換する。
ここではx-z平面で書き出しているが、 x-y平面での断面データなど、同様にとることが可能である。
サブルーチンmake_single_precision_fieldでは x-z面に平行な断面をとっている。その際、 その断面位置は j = slice_j = NY / 2 としている。NYが偶数の時、 この断面は厳密に言えばy=0にはなっていない。 なぜならgridモジュールできめたy方向の格子点の 定義によればy=0の面はj=NY/2とj=NY/2+1の2つの面 の中間にあるからである。正確にy=0面上での可視化 をしたいのであればこの2つの面上でのデータ の平均値をディスクに書き出すべきである。
[バグ] NYが奇数のときにちょうどy=0面に対応するのは j = slice_j = NY / 2 + 1 である。偶数のときにもこれでよい。 vor = .curl.vel enstrophy = vor.dot.vor
Arguments
Type Intent Optional Attributes Name
type(field__vector3d_t), intent(in) :: vel
速度場（3D）
real(kind=DR), intent(in), dimension(NX,NY,NZ) :: ps
圧力場（3D）
Calls
Called by
Contents
Source Code
make_single_precision_field
Source Code
  subroutine make_single_precision_field(vel,ps)
    !! シミュレーションで計算した速度場と圧力場
    !! のx-z平面での断面データを求める。
    !! その際、倍精度実数から単精度実数に型変換する。
    !!
    !! ここではx-z平面で書き出しているが、
    !! x-y平面での断面データなど、同様にとることが可能である。
    !!
    !! サブルーチンmake_single_precision_fieldでは
    !! x-z面に平行な断面をとっている。その際、
    !! その断面位置は
    !!     j = slice_j = NY / 2
    !! としている。NYが偶数の時、
    !! この断面は厳密に言えばy=0にはなっていない。
    !! なぜならgridモジュールできめたy方向の格子点の
    !! 定義によればy=0の面はj=NY/2とj=NY/2+1の2つの面
    !! の中間にあるからである。正確にy=0面上での可視化
    !! をしたいのであればこの2つの面上でのデータ
    !! の平均値をディスクに書き出すべきである。
    !!
    !! [バグ]
    !!   NYが奇数のときにちょうどy=0面に対応するのは
    !!     j = slice_j = NY / 2 + 1
    !!   である。偶数のときにもこれでよい。
    type(field__vector3d_t),       intent(in) :: vel !! 速度場（3D）
    real(DR), dimension(NX,NY,NZ), intent(in) :: ps  !! 圧力場（3D）
    integer(SI) :: slice_j = NY / 2    ! 断面をとるy座標の格子点位置
    type(field__vector3d_t)       :: vor       ! vorticity、渦度
    real(DR), dimension(NX,NY,NZ) :: enstrophy ! 渦度の2乗
!>        vor = .curl.vel
!>  enstrophy = vor.dot.vor
          vor = operator_curl(vel)
    enstrophy = operator_dot_product(vor,vor)
    Slice_vx = real(    vel%x(:,slice_j,:),SR)
    Slice_vy = real(    vel%y(:,slice_j,:),SR)
    Slice_vz = real(    vel%z(:,slice_j,:),SR)
    Slice_ps = real(       ps(:,slice_j,:),SR)
    Slice_en = real(enstrophy(:,slice_j,:),SR)
    call debug__print('called slicedata/make_single_precision_field.')
      ! デバッグモードがonの時には毎回メッセージを標準出力に
      ! 書き出す。コードが完成し、product runの段階に入ったら
      ! デバッグモードをoffにすれば、書き出しは抑制される。
      ! この行をコメントアウトする必要はない。
  end subroutine make_single_precision_field
Call graph
make_single_precision_field calls operator_curl, debug__print, operator_dot_product
operator_curl calls boundary_condition_vector
debug__print calls print_str_sint, print_str_dint, print_str_double, print_str, print_str_dint_double, print_str_sint_double
print_str_sint calls params__get_logical
print_str_dint calls params__get_logical
print_str_double calls ut__message, params__get_logical
print_str calls ut__message, params__get_logical
print_str_dint_double calls params__get_logical
print_str_sint_double calls params__get_logical
ut__message calls message_str_double, message_str_dint_double, message_str_float, message_decorated_str_dint, message_decorated_str, message_str_sint, message_str, message_str_sint_double_double, message_str_dint, message_str_dint_double_double, message_str_sint_double, message_decorated_str_sint
params__get_logical calls ut__message, ut__assert, ut__fatal
ut__assert calls ut__fatal
message_decorated_str_dint calls message_decorated_str
message_decorated_str_sint calls message_decorated_str
ut__fatal calls ut__message
slicedata__write calls make_single_precision_field
main_m calls slicedata__write