make_time_and_step_string – Smoke Ring
make_time_and_step_string Subroutine
17 statements
Source File
private subroutine make_time_and_step_string(t, step, string)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: t
integer, intent(in) :: step
character(len=TAG_NAME_MAX), intent(out) :: string
Calls
Called by
Contents
Source Code
make_time_and_step_string
Source Code
  subroutine make_time_and_step_string( t, step, string )
    real, intent(in) :: t
    integer, intent(in) :: step
    character(len=TAG_NAME_MAX), intent(out) :: string
    character(len=1), parameter :: CHAR_USCORE = "_"
    character(len=10) :: str_time_with_sign
    character(len=8)  :: str_step_with_sign
    character(len=9)  :: str_time_without_sign
    character(len=7)  :: str_step_without_sign
    str_time_with_sign = ut__real_to_str10( t )
    str_step_with_sign = ut__int_to_str8( step )
    call ut__assert( str_time_with_sign(1:1)=="+",  &
                    "vis2d_m/make_time_and_step_string(203): " //    &
                    "str_time_with_sign is strange." )
    call ut__assert( str_step_with_sign(1:1)=="+",  &
                    "vis2d_m/make_time_and_step_string(206): " //    &
                    "str_step_with_sign is strange." )
    str_time_without_sign = str_time_with_sign(2:10)
    str_step_without_sign = str_step_with_sign(2:8)
    string = "s=" // str_step_without_sign  &
                  // CHAR_USCORE //         &
             "t=" // str_time_without_sign
  end subroutine make_time_and_step_string
Call graph
make_time_and_step_string calls ut__assert, ut__int_to_str8, ut__real_to_str10
vis2d_plane_xy__draw calls make_time_and_step_string
vis2d_plane_xz__draw calls make_time_and_step_string