message_str_sint_double_double – Smoke Ring
message_str_sint_double_double Subroutine
6 statements
Source File
private subroutine message_str_sint_double_double(string, i1, d1, d2)
文字列 + 単精度整数 + 倍精度実数 + 倍精度実数の出力
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
メーセージ文字列
integer(kind=SI), intent(in) :: i1
書き出される整数
real(kind=DR), intent(in) :: d1
書き出される実数
real(kind=DR), intent(in) :: d2
書き出される実数
Called by
Contents
Source Code
message_str_sint_double_double
Source Code
  subroutine message_str_sint_double_double(string, i1, d1, d2)
    !! 文字列 + 単精度整数 + 倍精度実数 + 倍精度実数の出力
    character(len=*), intent(in) :: string  !! メーセージ文字列
    integer(SI), intent(in)      :: i1      !! 書き出される整数
    real(DR), intent(in)         :: d1, d2  !! 書き出される実数
    write(6,*) string, i1, d1, d2
  end subroutine message_str_sint_double_double
Call graph
ut__message calls message_str_sint_double_double
params__get_string calls ut__message, ut__fatal, ut__assert
slicedata__write calls ut__message, params__get_integer, debug__print, ut__assert, make_single_precision_field, solver__get_subfield
ut__fatal calls ut__message
print_str_double calls ut__message, params__get_logical
params__get_logical calls ut__message, ut__fatal, ut__assert
print_str calls ut__message, params__get_logical
params__get_double calls ut__message, ut__fatal, ut__assert
job__finalize calls ut__message
solver__set_time_step calls ut__message, params__get_logical, ut__assert, subfield_vel_tm
solver__diagnosis calls ut__message, debug__print, subfield_vel
params__get_integer calls ut__message, ut__fatal, ut__assert
slicedata__initialize calls params__get_string, debug__print
debug__print calls print_str_double, print_str, print_str_sint, print_str_dint, print_str_dint_double, print_str_sint_double
print_str_sint calls params__get_logical
print_str_dint calls params__get_logical
solver__initialize calls params__get_double, debug__print, set_drive_force_field
ut__assert calls ut__fatal
print_str_dint_double calls params__get_logical
job__karte_set calls ut__fatal
print_str_sint_double calls params__get_logical
main_m calls slicedata__write, job__finalize, solver__set_time_step, solver__diagnosis, params__get_integer, slicedata__initialize, debug__print, solver__initialize, solver__advance
the_equation calls debug__print, ut__assert, drive_force_factor
subfield_vel_tm calls debug__print
subfield_vel calls debug__print
set_drive_force_field calls debug__print
subfield_vel_tm_divv calls debug__print
make_single_precision_field calls debug__print
solver__advance calls debug__print, the_equation, subfield_vel_tm_divv
drive_force_factor calls ut__assert
solver__get_subfield calls subfield_vel_tm, subfield_vel, subfield_vel_tm_divv