min_max_string – Smoke Ring
min_max_string Function
8 statements
Source File
private function min_max_string(vmin, vmax) result(string)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: vmin
real, intent(in) :: vmax
Return Value character(len=TAG_NAME_MAX)
Calls
Called by
Contents
Source Code
min_max_string
Source Code
  function min_max_string( vmin, vmax ) result(string)
      real, intent(in) :: vmin, vmax
      character(len=TAG_NAME_MAX) :: string
      character(len=10) :: str10_vmax, str10_vmin
      str10_vmin = ut__real_to_str10( vmin )
      str10_vmax = ut__real_to_str10( vmax )
      string = 'vmin = '//str10_vmin//' vmax = '//str10_vmax
  end function min_max_string
Call graph
min_max_string calls ut__real_to_str10
draw_contour calls min_max_string
draw_contour_and_arrows calls min_max_string
vis2d_plane_xy__draw calls draw_contour_and_arrows
vis2d_plane_xz__draw calls draw_contour, draw_contour_and_arrows