operator_div – Smoke Ring
operator_div Function
17 statements
Source File
private function operator_div(a)
ベクトル場のdivergence
Arguments
Type Intent Optional Attributes Name
type(field__vector_t), intent(in) :: a
これのdivをとる
Return Value real(kind=DR), dimension(0:NXPP1,0:NYPP1,0:NZPP1)
結果
Calls
Called by
Contents
Source Code
operator_div
Source Code
  function operator_div( a )
    !! ベクトル場のdivergence
    type(field__vector_t), intent(in) :: a  !! これのdivをとる
    real(DR), dimension(0:NXPP1,0:NYPP1,0:NZPP1)        :: operator_div !! 結果
    integer :: i, j, k
    real(DR) :: dx1, dy1, dz1
    dx1 = grid%d1%x   ! x方向の偏微分演算用定数
    dy1 = grid%d1%y   ! y方向の偏微分演算用定数
    dz1 = grid%d1%z   ! z方向の偏微分演算用定数
    do k = 1, NZPP
      ! 境界上の格子点を飛ばして、シミュレーション領域内部
      ! の格子点上で差分法によりdivergenceを計算する
      do j = 1, NYPP
         do i = 1, NXPP
           operator_div(i,j,k) = dx1*(a%x(i+1,j,k)-a%x(i-1,j,k)) &
                               + dy1*(a%y(i,j+1,k)-a%y(i,j-1,k)) &
                               + dz1*(a%z(i,j,k+1)-a%z(i,j,k-1))
         end do
      end do
    end do
    call field__boundary_condition( operator_div )
      ! 境界の格子点は境界条件ルーチンで設定する
  end function operator_div
Call graph
operator_div calls field__boundary_condition, x, y, z
field__boundary_condition calls boundary_condition_scalar, boundary_condition_vector
boundary_condition_scalar calls mpiut__barrier, mpiut__exchange
boundary_condition_vector calls mpiut__barrier, mpiut__exchange
operator( .div. ) calls operator_div