operator_vector_divby_scalar – Smoke Ring
operator_vector_divby_scalar Function
8 statements
Source File
public function operator_vector_divby_scalar(vec, scalar)
ベクトル場の各成分をスカラー場で割る
Arguments
Type Intent Optional Attributes Name
type(field__vector3d_t), intent(in) :: vec
ベクトル場
real(kind=DR), intent(in), dimension(NX,NY,NZ) :: scalar
スカラー場
Return Value type(field__vector3d_t)
計算結果
Called by
Contents
Source Code
operator_vector_divby_scalar
Source Code
  function operator_vector_divby_scalar(vec,scalar)
    !! ベクトル場の各成分をスカラー場で割る
    type(field__vector3d_t),       intent(in) :: vec    !! ベクトル場
    real(DR), dimension(NX,NY,NZ), intent(in) :: scalar !! スカラー場
    type(field__vector3d_t) :: operator_vector_divby_scalar !! 計算結果
    operator_vector_divby_scalar%x = (vec%x) / scalar
    operator_vector_divby_scalar%y = (vec%y) / scalar
    operator_vector_divby_scalar%z = (vec%z) / scalar
  end function operator_vector_divby_scalar
Call graph
subfield_vel calls operator_vector_divby_scalar
subfield_vel_tm_divv calls operator_vector_divby_scalar
subfield_vel_tm calls operator_vector_divby_scalar
solver__advance calls subfield_vel_tm_divv
solver__get_subfield calls subfield_vel, subfield_vel_tm_divv, subfield_vel_tm
solver__set_time_step calls subfield_vel_tm
solver__diagnosis calls subfield_vel
main_m calls solver__advance, solver__set_time_step, solver__diagnosis, slicedata__write
slicedata__write calls solver__get_subfield