operator_curl – Smoke Ring
operator_curl Function
19 statements
Source File
private function operator_curl(a)
ベクトル場のcurl
Arguments
Type Intent Optional Attributes Name
type(field__vector_t), intent(in) :: a
これのcurlをとる
Return Value type(field__vector_t)
curlした結果
Calls
Called by
Contents
Source Code
operator_curl
Source Code
  function operator_curl( a )
    !! ベクトル場のcurl
    type(field__vector_t), intent(in) :: a !! これのcurlをとる
    type(field__vector_t) :: operator_curl !! curlした結果
    integer :: i, j, k
    real(DR) :: dx1, dy1, dz1
    dx1 = grid%d1%x  ! x方向の偏微分演算用定数
    dy1 = grid%d1%y  ! y方向の偏微分演算用定数
    dz1 = grid%d1%z  ! z方向の偏微分演算用定数
    do k = 1, NZPP
      ! 境界上の格子点を飛ばして、シミュレーション領域内部
      ! の格子点上で差分法によりcurlを計算する
      do j = 1, NYPP
        do i = 1, NXPP
          operator_curl%x(i,j,k) = dy1*(a%z(i,j+1,k)-a%z(i,j-1,k)) &
                                 - dz1*(a%y(i,j,k+1)-a%y(i,j,k-1))
          operator_curl%y(i,j,k) = dz1*(a%x(i,j,k+1)-a%x(i,j,k-1)) &
                                 - dx1*(a%z(i+1,j,k)-a%z(i-1,j,k))
          operator_curl%z(i,j,k) = dx1*(a%y(i+1,j,k)-a%y(i-1,j,k)) &
                                 - dy1*(a%x(i,j+1,k)-a%x(i,j-1,k))
        end do
      end do
    end do
    call field__boundary_condition( operator_curl )
      ! 境界の格子点は境界条件ルーチンで設定する
  end function operator_curl
Call graph
operator_curl calls field__boundary_condition, x, y, z
field__boundary_condition calls boundary_condition_scalar, boundary_condition_vector
boundary_condition_scalar calls mpiut__barrier, mpiut__exchange
boundary_condition_vector calls mpiut__barrier, mpiut__exchange
operator( .curl. ) calls operator_curl