operator_laplacian_vector – Smoke Ring
operator_laplacian_vector Function
19 statements
Source File
private function operator_laplacian_vector(a)
ベクトル場のラプラシアン
Arguments
Type Intent Optional Attributes Name
type(field__vector_t), intent(in) :: a
入力ベクトル場
Return Value type(field__vector_t)
計算結果
Calls
Called by
Contents
Source Code
operator_laplacian_vector
Source Code
  function operator_laplacian_vector( a )
    !! ベクトル場のラプラシアン
    type(field__vector_t), intent(in) :: a  !! 入力ベクトル場
    type(field__vector_t) :: operator_laplacian_vector !! 計算結果
    integer :: i, j, k
    real(DR) :: dx2, dy2, dz2
    dx2 = grid%d2%x   ! x方向の2階偏微分演算用定数
    dy2 = grid%d2%y   ! y方向の2階偏微分演算用定数
    dz2 = grid%d2%z   ! z方向の2階偏微分演算用定数
    do k = 1, NZPP
      ! 境界上の格子点を飛ばして、シミュレーション領域内部
      ! の格子点上で差分法により計算する
      do j = 1, NYPP
        do i = 1, NXPP
          operator_laplacian_vector%x(i,j,k)  &
               = dx2*(a%x(i+1,j,k)-2*a%x(i,j,k)+a%x(i-1,j,k))  &
               + dy2*(a%x(i,j+1,k)-2*a%x(i,j,k)+a%x(i,j-1,k))  &
               + dz2*(a%x(i,j,k+1)-2*a%x(i,j,k)+a%x(i,j,k-1))
          operator_laplacian_vector%y(i,j,k)  &
               = dx2*(a%y(i+1,j,k)-2*a%y(i,j,k)+a%y(i-1,j,k))  &
               + dy2*(a%y(i,j+1,k)-2*a%y(i,j,k)+a%y(i,j-1,k))  &
               + dz2*(a%y(i,j,k+1)-2*a%y(i,j,k)+a%y(i,j,k-1))
          operator_laplacian_vector%z(i,j,k)  &
               = dx2*(a%z(i+1,j,k)-2*a%z(i,j,k)+a%z(i-1,j,k))  &
               + dy2*(a%z(i,j+1,k)-2*a%z(i,j,k)+a%z(i,j-1,k))  &
               + dz2*(a%z(i,j,k+1)-2*a%z(i,j,k)+a%z(i,j,k-1))
        end do
     end do
    end do
    call field__boundary_condition( operator_laplacian_vector )
      ! 境界の格子点は境界条件ルーチンで設定する
  end function operator_laplacian_vector
Call graph
operator_laplacian_vector calls field__boundary_condition, x, y, z
field__boundary_condition calls boundary_condition_scalar, boundary_condition_vector
boundary_condition_scalar calls mpiut__barrier, mpiut__exchange
boundary_condition_vector calls mpiut__barrier, mpiut__exchange
operator( .laplacian. ) calls operator_laplacian_vector