operator_laplacian_scalar – Smoke Ring
operator_laplacian_scalar Function
17 statements
Source File
private function operator_laplacian_scalar(a)
スカラー場のラプラシアン
Arguments
Type Intent Optional Attributes Name
real(kind=DR), intent(in), dimension(0:NXPP1,0:NYPP1,0:NZPP1) :: a
入力スカラー場
Return Value real(kind=DR), dimension(0:NXPP1,0:NYPP1,0:NZPP1)
計算結果
Calls
Called by
Contents
Source Code
operator_laplacian_scalar
Source Code
  function operator_laplacian_scalar( a )
    !! スカラー場のラプラシアン
    real(DR), dimension(0:NXPP1,0:NYPP1,0:NZPP1), intent(in) :: a  !! 入力スカラー場
    real(DR), dimension(0:NXPP1,0:NYPP1,0:NZPP1) :: operator_laplacian_scalar !! 計算結果
    integer :: i, j, k
    real(DR) :: dx2, dy2, dz2
    dx2 = grid%d2%x   ! x方向の2階偏微分演算用定数
    dy2 = grid%d2%y   ! y方向の2階偏微分演算用定数
    dz2 = grid%d2%z   ! z方向の2階偏微分演算用定数
    do k = 1, NZPP
      ! 境界上の格子点を飛ばして、シミュレーション領域内部
      ! の格子点上で差分法により計算する
      do j = 1, NYPP
        do i = 1, NXPP
          operator_laplacian_scalar(i,j,k)  &
               = dx2*(a(i+1,j,k)-2*a(i,j,k)+a(i-1,j,k))  &
               + dy2*(a(i,j+1,k)-2*a(i,j,k)+a(i,j-1,k))  &
               + dz2*(a(i,j,k+1)-2*a(i,j,k)+a(i,j,k-1))
        end do
      end do
    end do
    call field__boundary_condition( operator_laplacian_scalar )
      ! 境界の格子点は境界条件ルーチンで設定する
  end function operator_laplacian_scalar
Call graph
operator_laplacian_scalar calls field__boundary_condition
field__boundary_condition calls boundary_condition_scalar, boundary_condition_vector
boundary_condition_scalar calls mpiut__barrier, mpiut__exchange
boundary_condition_vector calls mpiut__barrier, mpiut__exchange
operator( .laplacian. ) calls operator_laplacian_scalar