parallel__initialize – Smoke Ring
parallel__initialize Subroutine
70 statements
Source File
private subroutine parallel__initialize()
<
Type Bound
parallel_t
Arguments
None
Calls
Contents
Source Code
parallel__initialize
Source Code
  subroutine parallel__initialize
!!>
!    The following is the process allocation map. We do
!    not use the automatic allocation by MPI_Carte_create.
!
!               /     /     /     /     /|
!              /  12 / 13  / 14  / 15  / |
!             /-----/-----/-----/-----/  |           k
!            /     /     /     /     /|  /          /
!           /     /     /     /     / | /|         /
!          +-----+-----+-----+-----+  |/ |        +------ i
!    N     |     |     |     |     |  /  |        |
!    P     |  0  |  1  |  2  |  3  | /|  /        |
!    R     |     |     |     |     |/ | /|        |
!    O = 3 +-----+-----+-----+-----+  |/ |        |
!    C     |     |     |     |     |  /  |         j
!          |  4  |  5  |  6  |  7  | /|  /
!    Y     |     |     |     |     |/ | /
!          +-----+-----+-----+-----+  |/
!          |     |     |     |     |  /
!          |  8  |  9  | 10  | 11  | /
!          |     |     |     |     |/pos.index.k = rank / (mx*my)
!          +-----+-----+-----+-----+ pos.index.j = mod(rank,mx*my)/mx
!                                    pos.index.i = mod(rank,mx)
!                  NPROC_X = 4
!!<
    integer :: me, nprocs, comm
    call mpiut__init  ! No OpenMP
    ! call mpiut__init( MPI_THREAD_MULTIPLE )
    comm   = MPI_COMM_WORLD
    me     = mpiut__comm_rank( comm )
    nprocs = mpiut__comm_size( comm )
    call mpiut__assert( nprocs == NPROC_X*NPROC_Y*NPROC_Z,  &
                        'parallel_m/parallel__initialize: nprocs inconsistent.' )
    Parallel%comm    = comm
    Parallel%nprocs  = nprocs
    Parallel%rank%me = me
    Parallel%pos%index = Parallel%rank_to_pos_index( me )
    Parallel%rank%next = calc_rank_next( Parallel%pos%index )
                ! Sample: "p012_035_064"
    Parallel%pos%string = "p"                           & ! 1 letter
                    // ut__i2c3( Parallel%pos%index%i ) & ! 3 letters
                    // '_'                              & ! 1 letter
                    // ut__i2c3( Parallel%pos%index%j ) & ! 3 letters
                    // '_'                              & ! 1 letter
                    // ut__i2c3( Parallel%pos%index%k )   ! 3 letters
    associate ( periodic_pair => Parallel%periodic_pair,  &
                pos_index => Parallel%pos%index,          &
                have_xmax => Parallel%i_have_xmax,        &
                have_xmin => Parallel%i_have_xmin,        &
                have_ymax => Parallel%i_have_ymax,        &
                have_ymin => Parallel%i_have_ymin,        &
                have_zmax => Parallel%i_have_zmax,        &
                have_zmin => Parallel%i_have_zmin )
      periodic_pair%ip1 = MPI_PROC_NULL  ! Default values.
      periodic_pair%im1 = MPI_PROC_NULL  ! These will be
      periodic_pair%jp1 = MPI_PROC_NULL  ! overwritten.
      periodic_pair%jm1 = MPI_PROC_NULL
      periodic_pair%kp1 = MPI_PROC_NULL
      periodic_pair%km1 = MPI_PROC_NULL
      have_xmax = .false.  ! Default values.
      have_xmin = .false.  ! These will be
      have_ymax = .false.  ! overwritten.
      have_ymin = .false.
      have_zmax = .false.
      have_zmin = .false.
      if ( pos_index%i == NPROC_X-1 ) have_xmax = .true.
      if ( pos_index%i == 0         ) have_xmin = .true.
      if ( pos_index%j == NPROC_Y-1 ) have_ymax = .true.
      if ( pos_index%j == 0         ) have_ymin = .true.
      if ( pos_index%k == NPROC_Z-1 ) have_zmax = .true.
      if ( pos_index%k == 0         ) have_zmin = .true.
      if ( have_xmax ) periodic_pair%ip1 = me - NPROC_X + 1
      if ( have_xmin ) periodic_pair%im1 = me + NPROC_X - 1
      if ( have_ymax ) periodic_pair%jp1 = me - NPROC_X*(NPROC_Y-1)
      if ( have_ymin ) periodic_pair%jm1 = me + NPROC_X*(NPROC_Y-1)
      if ( have_zmax ) periodic_pair%kp1 = me - NPROC_X*NPROC_Y*(NPROC_Z-1)
      if ( have_zmin ) periodic_pair%km1 = me + NPROC_X*NPROC_Y*(NPROC_Z-1)
    end associate
    call iPrint
    call mpiut__barrier( comm )
  contains
    subroutine iPrint
      call mpiut__message_leader( comm,              &
                                'parallel_m: comm',  &
                                    Parallel%comm)
      call mpiut__message_leader( comm,                &
                                'parallel_m: nprocs',  &
                                    Parallel%nprocs)
      call mpiut__message_leader( comm,                 &
                                'parallel_m: rank.me',  &
                                    Parallel%rank%me)
      call mpiut__message_leader( comm,                     &
                                'parallel_m: pos.index.i',  &
                                    Parallel%pos%index%i)
      call mpiut__message_leader( comm,                     &
                                'parallel_m: pos.index.j',  &
                                    Parallel%pos%index%j)
      call mpiut__message_leader( comm,                     &
                                'parallel_m: pos.index.k',  &
                                    Parallel%pos%index%k)
      call mpiut__message_leader( comm,                    &
                                'parallel_m: pos.string',  &
                                    Parallel%pos%string)
      call mpiut__message_leader( comm,                       &
                                'parallel_m: rank.next.ip1',  &
                                    Parallel%rank%next%ip1)
      call mpiut__message_leader( comm,                       &
                                'parallel_m: rank.next.im1',  &
                                    Parallel%rank%next%im1)
      call mpiut__message_leader( comm,                       &
                                'parallel_m: rank.next.jp1',  &
                                    Parallel%rank%next%jp1)
      call mpiut__message_leader( comm,                       &
                                'parallel_m: rank.next.jm1',  &
                                    Parallel%rank%next%jm1)
      call mpiut__message_leader( comm,  &
                                'parallel_m: rank.next.kp1',  &
                                Parallel%rank%next%kp1)
      call mpiut__message_leader( comm,                       &
                                'parallel_m: rank.next.km1',  &
                                    Parallel%rank%next%km1)
      call mpiut__message_leader( comm,                   &
                                'parallel_m: have_xmax',  &
                                  Parallel%i_have_xmax)
      call mpiut__message_leader( comm,                   &
                                'parallel_m: have_xmin',  &
                                  Parallel%i_have_xmin)
      call mpiut__message_leader( comm,                   &
                                'parallel_m: have_ymax',  &
                                  Parallel%i_have_ymax)
      call mpiut__message_leader( comm,                   &
                                'parallel_m: have_ymin',  &
                                  Parallel%i_have_ymin)
      call mpiut__message_leader( comm,                   &
                                'parallel_m: have_zmax',  &
                                  Parallel%i_have_zmax)
      call mpiut__message_leader( comm,                   &
                                'parallel_m: have_zmin',  &
                                  Parallel%i_have_zmin)
      call mpiut__message_leader( comm,                          &
                                'parallel_m: periodic_pair.ip1', &
                                    Parallel%periodic_pair%ip1)
      call mpiut__message_leader( comm,                          &
                                'parallel_m: periodic_pair.im1', &
                                    Parallel%periodic_pair%im1)
      call mpiut__message_leader( comm,                          &
                                'parallel_m: periodic_pair.jp1', &
                                    Parallel%periodic_pair%jp1)
      call mpiut__message_leader( comm,                          &
                                'parallel_m: periodic_pair.jm1', &
                                    Parallel%periodic_pair%jm1)
      call mpiut__message_leader( comm,                          &
                                'parallel_m: periodic_pair.kp1', &
                                    Parallel%periodic_pair%kp1)
      call mpiut__message_leader( comm,                          &
                                'parallel_m: periodic_pair.km1', &
                                    Parallel%periodic_pair%km1)
    end subroutine iPrint
  end subroutine parallel__initialize
Call graph
parallel__initialize calls mpiut__assert, mpiut__barrier, mpiut__comm_rank, mpiut__comm_size, mpiut__init, calc_rank_next, rank_to_pos_index, ut__i2c3
calc_rank_next calls pos_ijk_to_rank