params__get_string – Smoke Ring
params__get_string Function
12 statements
Source File
public function params__get_string(variable)
このモジュールの外からの問い合わせに応じてnamelistデータを返す。 この関数は問い合わせ変数が文字列の場合。 この関数の前にnamelist__readが呼ばれている必要がある。 この点はassertで確認している。
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: variable
問い合わせ変数の名前
Return Value character(len=STRING_LENGTH_MAX)
その値
Calls
Called by
Contents
Source Code
params__get_string
Source Code
  function params__get_string(variable)
    !! このモジュールの外からの問い合わせに応じてnamelistデータを返す。
    !! この関数は問い合わせ変数が文字列の場合。
    !! この関数の前にnamelist__readが呼ばれている必要がある。
    !! この点はassertで確認している。
    character(len=*), intent(in) :: variable  !! 問い合わせ変数の名前
    character(len=STRING_LENGTH_MAX) :: params__get_string  !! その値
    call ut__assert(Read_done, &
                    '<params__get_string> Read params file first.')
    select case (variable)
      case                 ('Slicedata_tag')   ! 断面ファイル名に使う
        params__get_string = Slicedata_tag
      case default
        call ut__message('? arg = ', variable) ! 想定外
        call ut__fatal('<params__get_string> not in the params?')
    end select
  end function params__get_string
Call graph
params__get_string calls ut__message, ut__assert, ut__fatal
ut__message calls message_str_double, message_str_dint_double, message_str_float, message_decorated_str_dint, message_decorated_str, message_str_sint, message_str, message_str_sint_double_double, message_str_dint, message_str_dint_double_double, message_str_sint_double, message_decorated_str_sint
ut__assert calls ut__fatal
ut__fatal calls ut__message
message_decorated_str_dint calls message_decorated_str
message_decorated_str_sint calls message_decorated_str
slicedata__initialize calls params__get_string
main_m calls slicedata__initialize