params__get_integer – Smoke Ring
params__get_integer Function
14 statements
Source File
public function params__get_integer(variable)
このモジュールの外からの問い合わせに応じてnamelistデータを返す。 この関数は問い合わせ変数が整数の場合。 この関数の前にnamelist__readが呼ばれている必要がある。 この点はassertで確認している。
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: variable
問い合わせ変数の名前
Return Value integer(kind=SI)
その値
Calls
Called by
Contents
Source Code
params__get_integer
Source Code
  function params__get_integer(variable)
    !! このモジュールの外からの問い合わせに応じてnamelistデータを返す。
    !! この関数は問い合わせ変数が整数の場合。
    !! この関数の前にnamelist__readが呼ばれている必要がある。
    !! この点はassertで確認している。
    character(len=*), intent(in) :: variable    !! 問い合わせ変数の名前
    integer(SI) :: params__get_integer          !! その値
    call ut__assert(Read_done, &
                    '<params__get_integer> Read params file first.')
    select case (variable)
      case                  ('Slicedata_nskip')  ! 何ステップごとに
        params__get_integer = Slicedata_nskip    ! 断面をディスクに書き出すか
      case                  ('Total_nloop')      ! シミュレーションジョブ
        params__get_integer = Total_nloop        ! の実行最大ループ数
      case default                               ! 想定外
        call ut__message('? arg = ', variable)
        call ut__fatal('<params__get_integer> not in the params?')
    end select
  end function params__get_integer
Call graph
params__get_integer calls ut__message, ut__assert, ut__fatal
ut__message calls message_str_double, message_str_dint_double, message_str_float, message_decorated_str_dint, message_decorated_str, message_str_sint, message_str, message_str_sint_double_double, message_str_dint, message_str_dint_double_double, message_str_sint_double, message_decorated_str_sint
ut__assert calls ut__fatal
ut__fatal calls ut__message
message_decorated_str_dint calls message_decorated_str
message_decorated_str_sint calls message_decorated_str
main_m calls params__get_integer, slicedata__write
slicedata__write calls params__get_integer