params__get_double – Smoke Ring
params__get_double Function
14 statements
Source File
public function params__get_double(variable)
このモジュールの外からの問い合わせに応じてnamelistデータを返す。 この関数は問い合わせ変数が倍精度浮動小数点数の場合。 この関数の前にnamelist__readが呼ばれている必要がある。 この点はassertで確認している。
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: variable
問い合わせ変数の名前
Return Value real(kind=DR)
その値
Calls
Called by
Contents
Source Code
params__get_double
Source Code
  function params__get_double(variable)
    !! このモジュールの外からの問い合わせに応じてnamelistデータを返す。
    !! この関数は問い合わせ変数が倍精度浮動小数点数の場合。
    !! この関数の前にnamelist__readが呼ばれている必要がある。
    !! この点はassertで確認している。
    character(len=*), intent(in) :: variable  !! 問い合わせ変数の名前
    real(DR) :: params__get_double            !! その値
    call ut__assert(Read_done, &
                    '<params__get_double> Read params file first.')
    select case (variable)
      case                 ('Kappa')     ! 熱拡散率
        params__get_double = Kappa
      case                 ('Viscosity') ! 粘性率
        params__get_double = Viscosity
      case default                       ! そんなnamelist変数は想定外
        call ut__message('? arg = ', variable)
        call ut__fatal('<params__get_double> not in the params?')
    end select
  end function params__get_double
Call graph
params__get_double calls ut__message, ut__assert, ut__fatal
ut__message calls message_str_double, message_str_dint_double, message_str_float, message_decorated_str_dint, message_decorated_str, message_str_sint, message_str, message_str_sint_double_double, message_str_dint, message_str_dint_double_double, message_str_sint_double, message_decorated_str_sint
ut__assert calls ut__fatal
ut__fatal calls ut__message
message_decorated_str_dint calls message_decorated_str
message_decorated_str_sint calls message_decorated_str
solver__initialize calls params__get_double
main_m calls solver__initialize