params__get_logical – Smoke Ring
params__get_logical Function
12 statements
Source File
public function params__get_logical(variable)
このモジュールの外からの問い合わせに応じてnamelistデータを返す。 この関数は問い合わせ変数が論理値の場合。 この関数の前にnamelist__readが呼ばれている必要がある。 この点はassertで確認している。
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: variable
問い合わせ変数の名前
Return Value logical
その値
Calls
Called by
Contents
Source Code
params__get_logical
Source Code
  function params__get_logical(variable)
    !! このモジュールの外からの問い合わせに応じてnamelistデータを返す。
    !! この関数は問い合わせ変数が論理値の場合。
    !! この関数の前にnamelist__readが呼ばれている必要がある。
    !! この点はassertで確認している。
    character(len=*), intent(in) :: variable  !! 問い合わせ変数の名前
    logical :: params__get_logical            !! その値
    call ut__assert(Read_done, &
                    '<params__get_logical> Read params file first.')
    select case (variable)
      case                  ('Debug')  ! デバッグモードか否か
        params__get_logical = Debug
      case default                     ! 想定外
        call ut__message('? arg = ', variable)
        call ut__fatal('<params__get_logical> not in the params?')
    end select
  end function params__get_logical
Call graph
params__get_logical calls ut__message, ut__assert, ut__fatal
ut__message calls message_str_double, message_str_dint_double, message_str_float, message_decorated_str_dint, message_decorated_str, message_str_sint, message_str, message_str_sint_double_double, message_str_dint, message_str_dint_double_double, message_str_sint_double, message_decorated_str_sint
ut__assert calls ut__fatal
ut__fatal calls ut__message
message_decorated_str_dint calls message_decorated_str
message_decorated_str_sint calls message_decorated_str
print_str_sint calls params__get_logical
print_str_dint calls params__get_logical
print_str_double calls params__get_logical
print_str calls params__get_logical
print_str_dint_double calls params__get_logical
print_str_sint_double calls params__get_logical
solver__set_time_step calls params__get_logical, subfield_vel_tm
main_m calls solver__set_time_step, debug__print, slicedata__initialize, slicedata__write, solver__initialize, solver__advance, solver__diagnosis
debug__print calls print_str_sint, print_str_dint, print_str_double, print_str, print_str_dint_double, print_str_sint_double
slicedata__initialize calls debug__print
the_equation calls debug__print
subfield_vel_tm calls debug__print
slicedata__write calls debug__print, make_single_precision_field, solver__get_subfield
solver__initialize calls debug__print, set_drive_force_field
subfield_vel calls debug__print
set_drive_force_field calls debug__print
subfield_vel_tm_divv calls debug__print
make_single_precision_field calls debug__print
solver__advance calls debug__print, the_equation, subfield_vel_tm_divv
solver__diagnosis calls debug__print, subfield_vel
solver__get_subfield calls subfield_vel_tm, subfield_vel, subfield_vel_tm_divv