print_str_sint_double – Smoke Ring
print_str_sint_double Subroutine
8 statements
Source File
private subroutine print_str_sint_double(string, i1, d1)
Debugパラメータがtrueのとき文字列と整数と実数を出力する
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
出力文字列
integer(kind=SI), intent(in) :: i1
出力整数
real(kind=DR), intent(in) :: d1
出力実数
Calls
Called by
Contents
Source Code
print_str_sint_double
Source Code
  subroutine print_str_sint_double(string, i1, d1)
    !! Debugパラメータがtrueのとき文字列と整数と実数を出力する
    character(len=*), intent(in) :: string !! 出力文字列
    integer(SI), intent(in)      :: i1     !! 出力整数
    real(DR), intent(in)         :: d1     !! 出力実数
    if (params__get_logical('Debug')) then
      ! Debugをflaseに設定したときは何もしない
      call ut__message('debug: '//trim(string), i1, d1)
    end if
  end subroutine print_str_sint_double
Call graph
print_str_sint_double calls params__get_logical
params__get_logical calls ut__message, ut__assert, ut__fatal
ut__message calls message_str_double, message_str_dint_double, message_str_float, message_decorated_str_dint, message_decorated_str, message_str_sint, message_str, message_str_sint_double_double, message_str_dint, message_str_dint_double_double, message_str_sint_double, message_decorated_str_sint
ut__assert calls ut__fatal
ut__fatal calls ut__message
message_decorated_str_dint calls message_decorated_str
message_decorated_str_sint calls message_decorated_str
debug__print calls print_str_sint_double
slicedata__initialize calls debug__print
the_equation calls debug__print
subfield_vel_tm calls debug__print
slicedata__write calls debug__print, make_single_precision_field, solver__get_subfield
solver__initialize calls debug__print, set_drive_force_field
subfield_vel calls debug__print
set_drive_force_field calls debug__print
subfield_vel_tm_divv calls debug__print
make_single_precision_field calls debug__print
solver__advance calls debug__print, the_equation, subfield_vel_tm_divv
main_m calls debug__print, slicedata__initialize, slicedata__write, solver__initialize, solver__advance, solver__diagnosis, solver__set_time_step
solver__diagnosis calls debug__print, subfield_vel
solver__get_subfield calls subfield_vel_tm, subfield_vel, subfield_vel_tm_divv
solver__set_time_step calls subfield_vel_tm