set_drive_force_field – Smoke Ring
set_drive_force_field Subroutine
35 statements
Source File
private subroutine set_drive_force_field()
渦輪を駆動するための力の場を設定する その力はシミュレーション開始直後、短い時間だけかける。 空間的には局在した力を想定している。その形状は円筒形である。 円筒の軸はx軸上にある。
Arguments
None
Calls
Called by
Contents
Source Code
set_drive_force_field
Source Code
  subroutine set_drive_force_field
    !! 渦輪を駆動するための力の場を設定する
    !! その力はシミュレーション開始直後、短い時間だけかける。
    !! 空間的には局在した力を想定している。その形状は円筒形である。
    !! 円筒の軸はx軸上にある。
    integer(SI) :: i, j, k
    real(DR) :: xx, yy, zz
    real(DR) :: force_region_x_min, force_region_x_max
    real(DR) :: force_center_y, force_center_z
    real(DR) :: force_cylinder_diameter, force_cylinder_radius_sq
    real(DR), parameter :: THE_FORCE = 3.e3_DR
                                     ! 瞬間的な力の最大値。
                                     ! 試行錯誤で調整せよ。
    !
    !     +--------------------------------------+ ZMAX
    !     |                                      |
    !     |    +-------+                         |
    !     |    | Force |                         |
    !     |    +-------+                         |
    !     |                                      |
    !     +--------------------------------------+ ZMIN
    !    XMIN                                   XMAX
    !
    force_region_x_min = XMIN + (XMAX-XMIN)/5
      ! 力をかける局所円筒領域のx方向の最小値
    force_region_x_max = force_region_x_min + (XMAX-XMIN)/10
      ! 力をかける局所円筒領域のx方向の最大値
    force_center_y = (YMAX + YMIN) / 2
      ! 力をかける局所円筒領域の中心のy座標を中間にとる
    force_center_z = (ZMAX + ZMIN) / 2
      ! 力をかける局所円筒領域の中心のz座標を中間にとる
    force_cylinder_diameter  = min(YMAX-YMIN, ZMAX-ZMIN) / 4
      ! 力をかける局所円筒領域の直径
    force_cylinder_radius_sq = (force_cylinder_diameter/2)**2
      ! 力をかける局所円筒領域の半径の2乗
    do k = 2 , NZ-1
      ! 境界上の格子点を飛ばして、シミュレーション領域内部
      ! を回る3重do loop。境界上の格子点で値は境界条件で設定する。
      zz = grid%pos%z(k) - force_center_z    ! 力の中心からのz方向の距離
      do j = 2 , NY-1
        yy = grid%pos%y(j) - force_center_y  ! 力の中心からのy方向の距離
        do i = 2 , NX-1
          xx = grid%pos%x(i)                 ! これは格子点のx座標そのもの
          if ( (yy**2+zz**2) < force_cylinder_radius_sq  &
                        .and.  &
               (xx > force_region_x_min)  &
                        .and.  &
               (xx < force_region_x_max) ) then
            ! ここで半径そのもので比較するとsqrtの計算が必要になるが
            ! このように2乗同士で比較すれば不要。
            Drive_force%x(i,j,k) = THE_FORCE  ! いまはx方向だけに力がかかる
            Drive_force%y(i,j,k) = 0.0_DR     ! としている。斜め方向に力を
            Drive_force%z(i,j,k) = 0.0_DR     ! かけるにはこの部分を変更。
          else
            Drive_force%x(i,j,k) = 0.0_DR
            Drive_force%y(i,j,k) = 0.0_DR
            Drive_force%z(i,j,k) = 0.0_DR
          end if
        end do
      end do
    end do
    call field__boundary_condition(Drive_force)
      ! 上の3重do loopで設定していない境界上の格子点に力の場を
      ! 設定する。周期境界条件。
    call ut__assert(maxval(Drive_force%x)==THE_FORCE,  &
                    "<solver/set_drive_force_field> something is wrong.")
      ! 最大値がTHE_FORCEと仮定しているのでそうでなければ何かがおかしい。
    call debug__print("called solver/set_drive_force_field.")
      ! デバッグモードがonの時には毎回メッセージを標準出力に
      ! 書き出す。コードが完成し、product runの段階に入ったら
      ! デバッグモードをoffにすれば、書き出しは抑制される。
      ! この行をコメントアウトする必要はない。
  end subroutine set_drive_force_field
Call graph
set_drive_force_field calls field__boundary_condition, debug__print
field__boundary_condition calls boundary_condition_scalar, boundary_condition_vector, boundary_condition_fluid
debug__print calls print_str_sint, print_str_dint, print_str_double, print_str, print_str_dint_double, print_str_sint_double
print_str_sint calls params__get_logical
print_str_dint calls params__get_logical
print_str_double calls ut__message, params__get_logical
print_str calls ut__message, params__get_logical
print_str_dint_double calls params__get_logical
boundary_condition_fluid calls boundary_condition_scalar, boundary_condition_vector
print_str_sint_double calls params__get_logical
ut__message calls message_str_double, message_str_dint_double, message_str_float, message_decorated_str_dint, message_decorated_str, message_str_sint, message_str, message_str_sint_double_double, message_str_dint, message_str_dint_double_double, message_str_sint_double, message_decorated_str_sint
params__get_logical calls ut__message, ut__assert, ut__fatal
ut__assert calls ut__fatal
message_decorated_str_dint calls message_decorated_str
message_decorated_str_sint calls message_decorated_str
ut__fatal calls ut__message
solver__initialize calls set_drive_force_field
main_m calls solver__initialize