slicedata__write – Smoke Ring
slicedata__write Subroutine
14 statements
Source File
public subroutine slicedata__write(nloop, time, fluid)
断面データのディスクへの書き出し
Arguments
Type Intent Optional Attributes Name
integer(kind=DI), intent(in) :: nloop
現在のループカウンタ
real(kind=DR), intent(in) :: time
現在の時刻
type(field__fluid_t), intent(in) :: fluid
現在の流体データ
Calls
Called by
Contents
Source Code
slicedata__write
Source Code
  subroutine slicedata__write(nloop,time,fluid)
    !! 断面データのディスクへの書き出し
    integer(DI),          intent(in) :: nloop !! 現在のループカウンタ
    real(DR),             intent(in) :: time  !! 現在の時刻
    type(field__fluid_t), intent(in) :: fluid !! 現在の流体データ
    type(field__vector3d_t) :: vel
      ! 流れ速度ベクトル場。いまはナビエ・ストークス方程式の
      ! 基本変数を質量フラックスにしているのでこの流れ速度
      ! ベクトル場は基本変数ではなく、基本変数から計算される
      ! 二次的な量である。
    if ( params__get_integer('Slicedata_nskip') <= 0 ) return
                                      ! 何らかの理由で断面データの
                                      ! 出力をしないときには
                                      ! parameter中のSlicedata_nskip
                                      ! の値を負にする。
    if ( mod(nloop,params__get_integer('Slicedata_nskip')) /= 0 ) return
                                      ! parameter中のSlicedata_nskip
                                      ! の値が例えば10の時には
                                      ! 10ステップおきに断面データを計算し、
                                      ! ディスクに書き出す。
    call ut__assert(Initialize_done,"<slicedata__write> Forgot init?")
                                      ! モジュールの初期化終了確認
    call solver__get_subfield(fluid,vel)
                                      ! 流体の基本変数から速度場を求める
    call make_single_precision_field(vel,fluid%pressure)
                                      ! 断面データを作成
    write(FILE_SLICEDATA) nloop, real(time,SR),  &
                          Slice_vx, Slice_vy, Slice_vz,  &
                          Slice_ps, Slice_en
                                      ! ディスクへの書き出し
                                      ! 時刻も単精度に変換している
    call ut__message('#slice data saved at ', nloop, time)
                                      ! ここはデバッグモードがoffでも
                                      ! 書き出すようにしている。
                                      ! 断面データはそれほど頻繁に
                                      ! 書き出さない（この行まで到達しない）
                                      ! のでこの出力がたくさんあって
                                      ! 邪魔になることはあまりないと
                                      ! 予想できるためである。
    call debug__print('called slicedata__write.')
  end subroutine slicedata__write
Call graph
slicedata__write calls solver__get_subfield, debug__print, ut__message, ut__assert, make_single_precision_field, params__get_integer
solver__get_subfield calls subfield_vel, subfield_vel_tm_divv, subfield_vel_tm
debug__print calls print_str_dint, print_str_double, print_str, print_str_dint_double, print_str_sint, print_str_sint_double
ut__message calls message_str_float, message_decorated_str_dint, message_str_dint, message_str_sint_double, message_decorated_str, message_str_dint_double_double, message_decorated_str_sint, message_str_double, message_str_sint_double_double, message_str_sint, message_str, message_str_dint_double
ut__assert calls ut__fatal
make_single_precision_field calls debug__print, operator_curl, operator_dot_product
params__get_integer calls ut__message, ut__assert, ut__fatal
print_str_dint calls params__get_logical
subfield_vel calls debug__print, operator_vector_divby_scalar
print_str_double calls ut__message, params__get_logical
message_decorated_str_dint calls message_decorated_str
print_str calls ut__message, params__get_logical
print_str_dint_double calls params__get_logical
subfield_vel_tm_divv calls debug__print, operator_vector_divby_scalar, operator_div
operator_curl calls boundary_condition_vector
print_str_sint calls params__get_logical
print_str_sint_double calls params__get_logical
message_decorated_str_sint calls message_decorated_str
ut__fatal calls ut__message
subfield_vel_tm calls debug__print, operator_vector_divby_scalar
operator_div calls boundary_condition_scalar
params__get_logical calls ut__message, ut__assert, ut__fatal
main_m calls slicedata__write