slicedata__initialize – Smoke Ring
slicedata__initialize Subroutine
7 statements
Source File
public subroutine slicedata__initialize()
このモジュールの初期化
流体の場（fluid）の配列は決め打ち（つまりallocatableにしない）で 最初から3次元配列を確保している一方、ここではSlice_??配列を アロケータブルにしているのは、このslicedataモジュールは シミュレーションには必須ではないためである。 場合によってはこのslicedataモジュールを使わずに シュミレーションすることも考えられる。 例えば断面ではなく三次元の可視化をする時など。 そのような場合は、このslicedataモジュールは実際には 呼びたさないであろう。そのような時に備えて以下のように allocatableにしておけばメモリーを無駄遣いしない。
Arguments
None
Calls
Called by
Contents
Source Code
slicedata__initialize
Source Code
  subroutine slicedata__initialize
    !! このモジュールの初期化
    !!
    !! 流体の場（fluid）の配列は決め打ち（つまりallocatableにしない）で
    !! 最初から3次元配列を確保している一方、ここではSlice_??配列を
    !! アロケータブルにしているのは、このslicedataモジュールは
    !! シミュレーションには必須ではないためである。
    !! 場合によってはこのslicedataモジュールを使わずに
    !! シュミレーションすることも考えられる。
    !! 例えば断面ではなく三次元の可視化をする時など。
    !! そのような場合は、このslicedataモジュールは実際には
    !! 呼びたさないであろう。そのような時に備えて以下のように
    !! allocatableにしておけばメモリーを無駄遣いしない。
    allocate(Slice_vx(NX,NZ),   &
             Slice_vy(NX,NZ),   &
             Slice_vz(NX,NZ),   &
             Slice_ps(NX,NZ),   &
             Slice_en(NX,NZ))
    call debug__print('Slice data allocated.')
      ! デバッグモードがonの時には毎回メッセージを標準出力に
      ! 書き出す。コードが完成し、product runの段階に入ったら
      ! デバッグモードをoffにすれば、書き出しは抑制される。
      ! この行をコメントアウトする必要はない。
    open(FILE_SLICEDATA,                                &
         file=trim(params__get_string('Slicedata_tag')),  &
         form='unformatted')
      ! 断面データを書き出すファイルをオープン
    Initialize_done = .true.  ! 初期化終了のフラグをonにする
    call debug__print('called slicedata__initlilize')
  end subroutine slicedata__initialize
Call graph
slicedata__initialize calls debug__print, params__get_string
debug__print calls print_str_sint, print_str_dint, print_str_double, print_str, print_str_dint_double, print_str_sint_double
params__get_string calls ut__message, ut__assert, ut__fatal
print_str_sint calls params__get_logical
print_str_dint calls params__get_logical
ut__message calls message_str_double, message_str_dint_double, message_str_float, message_decorated_str_dint, message_decorated_str, message_str_sint, message_str, message_str_sint_double_double, message_str_dint, message_str_dint_double_double, message_str_sint_double, message_decorated_str_sint
ut__assert calls ut__fatal
print_str_double calls ut__message, params__get_logical
print_str calls ut__message, params__get_logical
print_str_dint_double calls params__get_logical
print_str_sint_double calls params__get_logical
ut__fatal calls ut__message
message_decorated_str_dint calls message_decorated_str
params__get_logical calls ut__message, ut__assert, ut__fatal
message_decorated_str_sint calls message_decorated_str
main_m calls slicedata__initialize