solver__set_time_step – Smoke Ring
solver__set_time_step Function
41 statements
Source File
private function solver__set_time_step(nloop, fluid)
CFL条件に基づいて時間刻み幅dtを設定する 初期化忘れ確認
基本流体データから速度場と温度場を計算
速度の最大値（ベクトルの長さの最大値）をもとめる ここでは配列演算を駆使して1行で書いているが 実際にはかなりの演算をしていることに注意。 これはバグではないが、maxvalとsqrtは交換すべき だろう。このままだと3次元配列の全要素にsqrt を掛けてからそのmaxvalをとっているが、これを 逆にした方が速いかもしれない。
初期条件では速度場がゼロなのでvmax=0となるが、あとで vmaxの割り算が出てくるので問題となる。それを回避するため ALMOST_ZEROが十分小さければよい。
音速の最大値 これも上と同じ理屈で、maxvalとsqrtは交換すべき だろう。このままだと3次元配列の全要素にsqrt を掛けてからそのmaxvalをとっているが、これを 逆にした方が速いかもしれない。
音速（の最大値）がほとんどゼロになるのは 何かがおかしいのですぐに停止
以下では、流れの速さ、音波、粘性拡散、熱拡散の4種類の CFL条件で決まる時間刻み幅をそれぞれこの順番に求めている。 CFL factor はここでは0.8と0.2にしているが、 これは精密な議論に基づいて決めたものではなく、 半経験的に決めた値である。 最後の2つ、粘性拡散と熱拡散によるCFL条件のための CFL factor の値 (0.2) というのは少々安全側に設定 しすぎているかもしれない。つまりもう少し大きくしても 問題ないかもしれない。
最終的な時間刻み幅は上記の4種類のdtの最小値できまる。
すべてのプロセスでの最小値をとる
出力が長くなるが、流体の状態を推測するのに便利なデータ。 SKIPをさらに10倍しているのは、それほど頻繁に出力する 必要は通常ないからである。 SKIPに一度dtを計算し直すが、それ以外は下の行を見れば分かる通り 前回のdtの値を流用する。その際、一度もdtを計算したことがなかったら まずいのでその検出をANOMALOUS_VALUEを使って検出している。
dt of the prev calc is saved. 新たに更新（または前回計算した）dtを返す。
Type Bound
solver_t
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nloop
ループカウンタ
type(fluid_t), intent(in) :: fluid
流体データ
Return Value real(kind=DR)
時間刻み幅 dt
Calls
Contents
Source Code
solver__set_time_step
Source Code
  function solver__set_time_step( nloop, fluid )
    !! CFL条件に基づいて時間刻み幅dtを設定する
    integer, intent(in) :: nloop  !! ループカウンタ
    type(fluid_t), intent(in) :: fluid  !! 流体データ
    real(DR) :: solver__set_time_step !! 時間刻み幅 dt
    type(field__vector_t) :: vel !! 速度場
    real(DR), dimension(0:NXPP1,0:NYPP1,0:NZPP1) :: tm  !! 温度場
    real(DR) :: vmax, sound_v
      !! 流れ速度の最大値と音速
    real(DR) :: dt_vel, dt_sound, dt_viscous, dt_kappa
      !! 流れ速度、音波、粘性拡散、熱拡散、それぞれで決まる時間刻み幅
      !! 実際のdtはこれらのなかで最も厳しい（小さい）値できまる。
    real(DR), parameter :: ALMOST_ZERO = 1.e-20_DR
      !! ゼロ割り演算回避のために使う小さい値
    real(DR), parameter :: ANOMALOUS_VALUE = -999.999_DR
      !! dtとしてありそうにない値（すぐ下で使う）
    real(DR) :: dt_local
      !! 各MPIプロセスで計算した時間刻み幅
    real(DR), save :: dt_global = ANOMALOUS_VALUE
      !! 時間刻み幅。全プロセスの最小値。
      !! 初期設定でなんらかの失敗した場合を検出するため
      !! 最初はありそうない値を設定しておくが、
      !! CFL条件に基づいて正しい値を一度設定したらその後は
      !! この宣言文にはsave属性がついているので、
      !! この関数を抜けたあともその値を覚えている。
    integer, parameter :: SKIP = 20
      !! dtを毎ステップ計算するのは大変（かなりの時間がかかる）
      !! のでこのSKIPステップに一度だけ計算する。毎ステップ計算する
      !! してもdtは1ステップでそれほど大きく変化しないからである。
      !! ただし、計算が破綻（発散）するような場合は例外である。
    call ut__assert( Initialize_done,  &
                     "solver_m(682): Forgot init?" )
      !! 初期化忘れ確認
    if ( mod(nloop,SKIP)==0 ) then ! ほとんどの場合は、前回計算したdtを使う。
      call subfield_vel_tm(fluid,vel,tm)
        !! 基本流体データから速度場と温度場を計算
      vmax = maxval(sqrt(vel%x**2+vel%y**2+vel%z**2))
        !! 速度の最大値（ベクトルの長さの最大値）をもとめる
        !! ここでは配列演算を駆使して1行で書いているが
        !! 実際にはかなりの演算をしていることに注意。
        !! これはバグではないが、maxvalとsqrtは交換すべき
        !! だろう。このままだと3次元配列の全要素にsqrt
        !! を掛けてからそのmaxvalをとっているが、これを
        !! 逆にした方が速いかもしれない。
      vmax = max(vmax,ALMOST_ZERO)
        !! 初期条件では速度場がゼロなのでvmax=0となるが、あとで
        !! vmaxの割り算が出てくるので問題となる。それを回避するため
        !! ALMOST_ZEROが十分小さければよい。
      sound_v = GAMMA*maxval(sqrt(GASS_CONST_FOR_AIR*tm))
        !! 音速の最大値
        !! これも上と同じ理屈で、maxvalとsqrtは交換すべき
        !! だろう。このままだと3次元配列の全要素にsqrt
        !! を掛けてからそのmaxvalをとっているが、これを
        !! 逆にした方が速いかもしれない。
      call ut__assert( sound_v > ALMOST_ZERO,  &
                       "solver_m(711): sound_v=0?" )
        !! 音速（の最大値）がほとんどゼロになるのは
        !! 何かがおかしいのですぐに停止
      !! 以下では、流れの速さ、音波、粘性拡散、熱拡散の4種類の
      !! CFL条件で決まる時間刻み幅をそれぞれこの順番に求めている。
      dt_vel     = 0.8_DR*grid%delta_min/vmax
      dt_sound   = 0.8_DR*grid%delta_min/sound_v
      dt_viscous = 0.2_DR*(grid%delta_min**2)/Viscosity
      dt_kappa   = 0.2_DR*(grid%delta_min**2)/Gamma1_kappa
        !! CFL factor はここでは0.8と0.2にしているが、
        !! これは精密な議論に基づいて決めたものではなく、
        !! 半経験的に決めた値である。
        !! 最後の2つ、粘性拡散と熱拡散によるCFL条件のための
        !! CFL factor の値 (0.2) というのは少々安全側に設定
        !! しすぎているかもしれない。つまりもう少し大きくしても
        !! 問題ないかもしれない。
      dt_local = min(dt_vel, dt_sound, dt_viscous, dt_kappa)
        !! 最終的な時間刻み幅は上記の4種類のdtの最小値できまる。
      call mpiut__minval( Parallel%comm, dt_local, dt_global )
        !! すべてのプロセスでの最小値をとる
      if ( mod(nloop,SKIP*100)==0 ) then
        !! 出力が長くなるが、流体の状態を推測するのに便利なデータ。
        !! SKIPをさらに10倍しているのは、それほど頻繁に出力する
        !! 必要は通常ないからである。
        associate ( comm => Parallel%comm )
          call mpiut__message_leader( comm, '     nloop', nloop      )
          call mpiut__message_leader( comm, '      vmax', vmax       )
          call mpiut__message_leader( comm, '    dt_vel', dt_vel     )
          call mpiut__message_leader( comm, '  dt_sound', dt_sound   )
          call mpiut__message_leader( comm, '  dt_kappa', dt_kappa   )
          call mpiut__message_leader( comm, 'dt_viscous', dt_viscous )
          call mpiut__message_leader( comm, '    --> dt', dt_global  )
        end associate
      end if
    end if
    call ut__assert( dt_global /= ANOMALOUS_VALUE,  &
                     "solver_m(752): dt init failed?" )
      !! SKIPに一度dtを計算し直すが、それ以外は下の行を見れば分かる通り
      !! 前回のdtの値を流用する。その際、一度もdtを計算したことがなかったら
      !! まずいのでその検出をANOMALOUS_VALUEを使って検出している。
    solver__set_time_step = dt_global   !! dt of the prev calc is saved.
      !! 新たに更新（または前回計算した）dtを返す。
  end function solver__set_time_step
Call graph
solver__set_time_step calls mpiut__message_leader, mpiut__minval, subfield_vel_tm, ut__assert