solver__advance – Smoke Ring
solver__advance Subroutine
36 statements
Source File
public subroutine solver__advance(t, dt, fluid)
4段4次ルンゲ・クッタ積分法による時間積分の実行
Note
ここでは教科書に書かれている古典的な4段4次の ルンゲ・クッタ積分法をそのまま実装している。 作業用の構造体を5つ使用している（dfluid01からdfluid04とgluid） これらの作業変数の数を減らし、メモリを節約にするためには Runge-Kutta-Gill法などの方法がある。
Note
速度（vel）、温度（tm）, 速度の発散（divv）などの配列などは このスキームでは基本変数から毎回計算すべき一種の作業配列である。 したがって、このモジュール内の他の場所（サブルーチン・関数）でも これらの変数（3次元の大きな配列）を宣言・使用している。 使用メモリを節約するためにはこれらの作業配列は共通のものを 一つづつ用意するというのも可能である。しかし、そうするとコードが 読みにくくなるであろう。
Arguments
Type Intent Optional Attributes Name
real(kind=DR), intent(inout) :: t
時刻
real(kind=DR), intent(in) :: dt
時間刻み幅
type(field__fluid_t), intent(inout) :: fluid
流体データ
Calls
Called by
Contents
Source Code
solver__advance
Source Code
  subroutine solver__advance(t,dt,fluid)
    !! 4段4次ルンゲ・クッタ積分法による時間積分の実行
    !!
    !! @note
    !!   ここでは教科書に書かれている古典的な4段4次の
    !!   ルンゲ・クッタ積分法をそのまま実装している。
    !!   作業用の構造体を5つ使用している（dfluid01からdfluid04とgluid）
    !!   これらの作業変数の数を減らし、メモリを節約にするためには
    !!   Runge-Kutta-Gill法などの方法がある。
    !!
    !! @note
    !!   速度（vel）、温度（tm）, 速度の発散（divv）などの配列などは
    !!   このスキームでは基本変数から毎回計算すべき一種の作業配列である。
    !!   したがって、このモジュール内の他の場所（サブルーチン・関数）でも
    !!   これらの変数（3次元の大きな配列）を宣言・使用している。
    !!   使用メモリを節約するためにはこれらの作業配列は共通のものを
    !!   一つづつ用意するというのも可能である。しかし、そうするとコードが
    !!   読みにくくなるであろう。
    real(DR), intent(inout) :: t  !! 時刻
    real(DR), intent(in)    :: dt !! 時間刻み幅
    type(field__fluid_t), intent(inout)  :: fluid !! 流体データ
    real(DR), parameter :: ONE_SIXTH = 1.0_DR / 6.0_DR ! 演算数節約の
    real(DR), parameter :: ONE_THIRD = 1.0_DR / 3.0_DR ! ために定義
    type(field__vector3d_t)       :: vel   ! 速度場
    real(DR), dimension(NX,NY,NZ) :: tm    ! 温度場
    real(DR), dimension(NX,NY,NZ) :: divv  ! 速度場の発散
    type(field__fluid_t) :: dfluid01, dfluid02, dfluid03, dfluid04
      ! 古典的な4段4次ルンゲ・クッタ積分法に必要な4つの作業配列
      ! サイズが大きいことに注意。
    type(field__fluid_t) :: gluid  ! work variable
      ! さらにもう一つの作業配列
      ! サイズが大きいことに注意。
    !---ルンゲ・クッタの第1段---!
    call subfield_vel_tm_divv(fluid,vel,tm,divv)
      ! 基本変数から副次的変数である速度、温度、速度の発散を求める
    dfluid01 = the_equation(t, dt,  &
                            vel%x, vel%y, vel%z, tm, divv,  &
                            fluid%flux%x, fluid%flux%y, fluid%flux%z,  &
                            fluid%pressure)
    t = t + dt/2
      ! 渦輪を駆動する力は時刻（t）の関数として設定しているので、
      ! いま解いているナビエ・ストークス方程式は時間に陽に依存する。
    !---ルンゲ・クッタの第2段---!
![  gluid = fluid + dfluid01*0.5_DR
    dfluid01 = operator_fluid_times_real(dfluid01,0.5_DR)
    gluid    = operator_fluid_add(fluid,dfluid01)
      ! Fortranコンパイラが自己定義演算子をきちんと処理できる
      ! 場合は上の簡潔な記述の方が（読みやすいので）好ましい。
    call subfield_vel_tm_divv(gluid,vel,tm,divv)
    dfluid02 = the_equation(t, dt,  &
                            vel%x, vel%y, vel%z, tm, divv,  &
                            gluid%flux%x, gluid%flux%y, gluid%flux%z,  &
                            gluid%pressure)
    !---ルンゲ・クッタの第3段---!
![  gluid = fluid + dfluid02*0.5_DR
    dfluid02 = operator_fluid_times_real(dfluid02,0.5_DR)
    gluid    = operator_fluid_add(fluid,dfluid02)
      ! Fortranコンパイラが自己定義演算子をきちんと処理できる
      ! 場合は上の簡潔な記述の方が（読みやすいので）好ましい。
    call subfield_vel_tm_divv(gluid,vel,tm,divv)
    dfluid03 = the_equation(t, dt,  &
                            vel%x, vel%y, vel%z, tm, divv,  &
                            gluid%flux%x, gluid%flux%y, gluid%flux%z,  &
                            gluid%pressure)
    t = t + dt/2
      ! 繰り返すが、渦輪を駆動する力は時刻（t）の関数として設定しているので、
      ! いま解いているナビエ・ストークス方程式は時間に陽に依存する。
    !---ルンゲ・クッタの第4段---!
![  gluid = fluid + dfluid03
    gluid = operator_fluid_add(fluid,dfluid03)
      ! Fortranコンパイラが自己定義演算子をきちんと処理できる
      ! 場合は上の簡潔な記述の方が（読みやすいので）好ましい。
    call subfield_vel_tm_divv(gluid,vel,tm,divv)
    dfluid04 = the_equation(t, dt,  &
                            vel%x, vel%y, vel%z, tm, divv,  &
                            gluid%flux%x, gluid%flux%y, gluid%flux%z,  &
                            gluid%pressure)
    !--- 最終結果 ---!
![  fluid = fluid  &
![        + ONE_SIXTH*(dfluid01 + 2*dfluid02 + 2*dfluid03 + dfluid04)
    dfluid01 = operator_fluid_times_real(dfluid01,ONE_SIXTH)
    dfluid02 = operator_fluid_times_real(dfluid02,ONE_THIRD)
    dfluid03 = operator_fluid_times_real(dfluid03,ONE_THIRD)
    dfluid04 = operator_fluid_times_real(dfluid04,ONE_SIXTH)
    fluid = operator_fluid_add(fluid,dfluid01)
    fluid = operator_fluid_add(fluid,dfluid02)
    fluid = operator_fluid_add(fluid,dfluid03)
    fluid = operator_fluid_add(fluid,dfluid04)
      ! Fortranコンパイラが自己定義演算子をきちんと処理できる
      ! 場合は一番上の簡潔な記述の方が（読みやすいので）好ましい。
    call debug__print("called solver__advance.")
      ! デバッグモードがonの時には毎回メッセージを標準出力に
      ! 書き出す。コードが完成し、product runの段階に入ったら
      ! デバッグモードをoffにすれば、書き出しは抑制される。
      ! この行をコメントアウトする必要はない。
  end subroutine solver__advance
Call graph
solver__advance calls debug__print, the_equation, operator_fluid_times_real, operator_fluid_add, subfield_vel_tm_divv
debug__print calls print_str_sint, print_str_dint, print_str_double, print_str, print_str_dint_double, print_str_sint_double
the_equation calls debug__print, ut__assert, field__boundary_condition, drive_force_factor
subfield_vel_tm_divv calls debug__print, operator_div, operator_vector_divby_scalar
print_str_sint calls params__get_logical
operator_div calls boundary_condition_scalar
print_str_dint calls params__get_logical
ut__assert calls ut__fatal
print_str_double calls ut__message, params__get_logical
print_str calls ut__message, params__get_logical
print_str_dint_double calls params__get_logical
print_str_sint_double calls params__get_logical
field__boundary_condition calls boundary_condition_scalar, boundary_condition_vector, boundary_condition_fluid
drive_force_factor calls ut__assert
ut__message calls message_str_double, message_str_dint_double, message_str_float, message_decorated_str_dint, message_decorated_str, message_str_sint, message_str, message_str_sint_double_double, message_str_dint, message_str_dint_double_double, message_str_sint_double, message_decorated_str_sint
params__get_logical calls ut__assert, ut__message, ut__fatal
boundary_condition_fluid calls boundary_condition_scalar, boundary_condition_vector
ut__fatal calls ut__message
message_decorated_str_dint calls message_decorated_str
message_decorated_str_sint calls message_decorated_str
main_m calls solver__advance