solver__diagnosis – Smoke Ring
solver__diagnosis Subroutine
50 statements
Source File
public subroutine solver__diagnosis(nloop, time, fluid)
流体の「健康状態」を診断する
Arguments
Type Intent Optional Attributes Name
integer(kind=DI), intent(in) :: nloop
ループカウンタ
real(kind=DR), intent(in) :: time
シミュレーション時刻
type(field__fluid_t), intent(in) :: fluid
流体データ
Calls
Called by
Contents
Source Code
solver__diagnosis
Source Code
  subroutine solver__diagnosis(nloop,time,fluid)
    !! 流体の「健康状態」を診断する
    integer(DI),          intent(in) :: nloop  !! ループカウンタ
    real(DR),             intent(in) :: time   !! シミュレーション時刻
    type(field__fluid_t), intent(in) :: fluid  !! 流体データ
    integer(SI), parameter :: SKIP = 100
      ! このルーチンは結構計算負荷が高いので、
      ! 毎ステップではなく、SKIPステップごとに診断を実行する
    real(DR), parameter :: ABNORMALLY_LARGE = 1.e20_DR
      ! これよりも物理量が大きくなったら異常が生じたと判断する
    type(field__vector3d_t) :: vel
      ! 流れの速度場
    if ( mod(nloop,SKIP) /= 0 ) return
      ! このルーチンは結構計算負荷が高いので、
      ! 毎ステップではなく、SKIPステップごとに診断を実行する
    if ( job__karte%state /= "fine" ) return ! Already in error state.
      ! ジョブの健康状態がfine（つまり健康）以外の値に
      ! 設定する可能性があるのはここ以外にもある（例えばmain.f90の
      ! メインループでシミュレーションのループカウンタが最大値が達するなど）
      ! そのような場合、どうせこの後、ジョブの停止処理に入るので、
      ! これ以上計算を進めなくてもよい。
    if ( maxval(fluid%flux%x) > ABNORMALLY_LARGE ) then
      ! 質量フラックスのx成分の最大値が異常に大きい
      ! これはバグである。absを入れ忘れている。
      call ut__message("<solver__diagnosis> Massflux_x overflow.")
      call job__karte%set("over_flow")
      return
        ! これ以上計算しても無駄（すぐに終了処理に入るべし）
    end if
    if ( maxval(fluid%flux%y) > ABNORMALLY_LARGE ) then
      ! 質量フラックスのy成分の最大値が異常に大きい
      ! これもバグである。absを入れ忘れている。
      call ut__message("<solver__diagnosis> Massflux_y overflow.")
      call job__karte%set("over_flow")
      return
        ! これ以上計算しても無駄（すぐに終了処理に入るべし）
    end if
    if ( maxval(fluid%flux%z) > ABNORMALLY_LARGE ) then
      ! 質量フラックスのz成分の最大値が異常に大きい
      ! これもバグである。absを入れ忘れている。
      call ut__message("<solver__diagnosis> Massflux_z overflow.")
      call job__karte%set("over_flow")
      return
        ! これ以上計算しても無駄（すぐに終了処理に入るべし）
    end if
    if ( maxval(fluid%density) > ABNORMALLY_LARGE ) then
      ! 質量が異常に大きい
      call ut__message("<solver__diagnosis> Density overflow.")
      call job__karte%set("over_flow")
      return
        ! これ以上計算しても無駄（すぐに終了処理に入るべし）
    end if
    if ( maxval(fluid%pressure) > ABNORMALLY_LARGE ) then
      ! 圧力が異常に大きい
      call ut__message("<solver__diagnosis> Pressure overflow.")
      call job__karte%set("over_flow")
      return
        ! これ以上計算しても無駄（すぐに終了処理に入るべし）
    end if
    if ( minval(fluid%pressure) < 0.0_DR ) then
      ! 圧力が負になってしまっている
      call ut__message("<solver__diagnosis> Negative pressure.")
      call job__karte%set("negative_anormaly")
      return
        ! これ以上計算しても無駄（すぐに終了処理に入るべし）
    end if
    if ( minval(fluid%density) < 0.0_DR ) then
      ! 密度が負になってしまっている
      call ut__message("<solver__diagnosis> Negative density.")
      call job__karte%set("negative_anormaly")
      return
        ! これ以上計算しても無駄（すぐに終了処理に入るべし）
    end if
    call subfield_vel(fluid,vel)
      ! 基本流れデータから副次的な速度場データを求める
    call ut__message('#max vel:',      nloop, time,  &
                     sqrt(maxval(vel%x**2+vel%y**2+vel%z**2)))
      ! 速度の最大値（ベクトルの長さ）を計算し標準出力に書き出す
      ! わずか1行で書いているが、実際にはここにかなりの計算が
      ! 含まれている。vel%x**2という配列演算は実際には3重do loop
      ! であり、maxval関数はその引数の3次元配列をとっている。
      ! つまり全要素中の最大値をとっている。そして最後に
      ! sqrtをとって振幅（ベクトルの長さ）を計算している。
    call ut__message('#flow energy: ', nloop, time,  &
![                                    .energyintegral.fluid)
                                       operator_energyintegral(fluid))
      ! ここでもFortranコンパイラが許せば.energyintegral.という
      ! 簡潔な演算子表現を使ったほうがよい。ここでもこの1行の
      ! 実行にはかなりの演算（速度ベクトル場のx,y,z3成分の2乗和に
      ! 資料密度を掛けたもの体積積分）が必要であることに注意。
    call ut__message('#total mass: ',  nloop, time,  &
![                                    .scalarintegral.(fluid%density))
                               operator_scalarintegral(fluid%density))
      ! 上と同様。こちらのほうは単なる密度場の体積積分なので
      ! 演算量は少ないが、シミュレーション領域全体に渡る体積積分
      ! なので計算量は大きいことに間違いない。
    call debug__print('called solver__diagnosis.')
      ! デバッグモードがonの時には毎回メッセージを標準出力に
      ! 書き出す。コードが完成し、product runの段階に入ったら
      ! デバッグモードをoffにすれば、書き出しは抑制される。
      ! この行をコメントアウトする必要はない。
  end subroutine solver__diagnosis
Call graph
solver__diagnosis calls debug__print, ut__message, subfield_vel, operator_scalarintegral, operator_energyintegral
debug__print calls print_str_dint, print_str_double, print_str, print_str_dint_double, print_str_sint, print_str_sint_double
ut__message calls message_str_float, message_decorated_str_dint, message_str_dint, message_str_sint_double, message_decorated_str, message_str_dint_double_double, message_decorated_str_sint, message_str_double, message_str_sint_double_double, message_str_sint, message_str, message_str_dint_double
subfield_vel calls debug__print, operator_vector_divby_scalar
operator_energyintegral calls operator_dot_product
print_str_dint calls params__get_logical
print_str_double calls ut__message, params__get_logical
message_decorated_str_dint calls message_decorated_str
print_str calls ut__message, params__get_logical
print_str_dint_double calls params__get_logical
print_str_sint calls params__get_logical
print_str_sint_double calls params__get_logical
message_decorated_str_sint calls message_decorated_str
params__get_logical calls ut__message, ut__assert, ut__fatal
ut__assert calls ut__fatal
ut__fatal calls ut__message
main_m calls solver__diagnosis