solver__initialize – Smoke Ring
solver__initialize Subroutine
15 statements
Source File
public subroutine solver__initialize(fluid)
モジュールの初期化
Arguments
Type Intent Optional Attributes Name
type(field__fluid_t), intent(out) :: fluid
流体データ
Calls
Called by
Contents
Source Code
solver__initialize
Source Code
  subroutine solver__initialize(fluid)
    !! モジュールの初期化
    type(field__fluid_t), intent(out) :: fluid  !! 流体データ
    real(DR) :: kappa  ! 空気の熱拡散率
    ! 物理パラメータの設定
    Viscosity = params__get_double('Viscosity') ! 空気の粘性率
    kappa     = params__get_double('Kappa')     ! 空気の熱拡散率
      ! Viscosityと違ってkappaの頭文字が大文字になっていない、つまり
      ! このモジュールのグローバルスコープを持つ変数としていない
      ! のはナビエ・ストークス方程式には下で定義するGamma1_kappa
      ! という量のみを通じてkappaが出てくるからである。
    Gamma1_kappa = (Gamma-1)*kappa
      ! gammaは比熱比、つまり定積比熱と定圧比熱の比である。
      ! 統計力学で習うように、この値は流体（気体）を構成する
      ! 分子の構造（自由度）で決まる。
    ! 流体の初期条件の設定
    fluid%pressure = 1.013e5_DR  ! 1013 hPa (一気圧)
    fluid%density  = 1.293_DR    ! kg/m^3 (空気の密度)
![  fluid%flux     = 0.0_DR      ! 初期速度なし（流れなし）
    fluid%flux%x   = 0.0_DR      ! 初期速度なし（流れなし）
    fluid%flux%y   = 0.0_DR
    fluid%flux%z   = 0.0_DR
      ! コンパイラが許す場合は上の簡潔な代入表現の方が望ましい
    ! 渦輪を駆動するための力の場の設定
    call set_drive_force_field
    Initialize_done = .true.
      ! モジュール初期化終了フラグ
    call debug__print("called solver__initialize.")
      ! デバッグモードがonの時には毎回メッセージを標準出力に
      ! 書き出す。コードが完成し、product runの段階に入ったら
      ! デバッグモードをoffにすれば、書き出しは抑制される。
      ! この行をコメントアウトする必要はない。
  end subroutine solver__initialize
Call graph
solver__initialize calls debug__print, params__get_double, set_drive_force_field
debug__print calls print_str_sint, print_str_dint, print_str_double, print_str, print_str_dint_double, print_str_sint_double
params__get_double calls ut__message, ut__assert, ut__fatal
set_drive_force_field calls debug__print, field__boundary_condition
print_str_sint calls params__get_logical
print_str_dint calls params__get_logical
ut__message calls message_str_double, message_str_dint_double, message_str_float, message_decorated_str_dint, message_decorated_str, message_str_sint, message_str, message_str_sint_double_double, message_str_dint, message_str_dint_double_double, message_str_sint_double, message_decorated_str_sint
ut__assert calls ut__fatal
print_str_double calls ut__message, params__get_logical
print_str calls ut__message, params__get_logical
print_str_dint_double calls params__get_logical
print_str_sint_double calls params__get_logical
field__boundary_condition calls boundary_condition_scalar, boundary_condition_vector, boundary_condition_fluid
ut__fatal calls ut__message
message_decorated_str_dint calls message_decorated_str
params__get_logical calls ut__message, ut__assert, ut__fatal
boundary_condition_fluid calls boundary_condition_scalar, boundary_condition_vector
message_decorated_str_sint calls message_decorated_str
main_m calls solver__initialize