subfield_vel_tm_divv – Smoke Ring
subfield_vel_tm_divv Subroutine
10 statements
Source File
private subroutine subfield_vel_tm_divv(fluid, vel, tm, divv)
fluidの基本変数から二次的な場（速度ベクトル場velと 温度場tmと速度の発散divv）をもとめる。
Arguments
Type Intent Optional Attributes Name
type(field__fluid_t), intent(in) :: fluid
流体基本場
type(field__vector3d_t), intent(out) :: vel
流れ場
real(kind=DR), intent(out), dimension(NX,NY,NZ) :: tm
温度場
real(kind=DR), intent(out), dimension(NX,NY,NZ) :: divv
流れの発散
Calls
Called by
Contents
Source Code
subfield_vel_tm_divv
Source Code
  subroutine subfield_vel_tm_divv(fluid,vel,tm,divv)
    !! fluidの基本変数から二次的な場（速度ベクトル場velと
    !! 温度場tmと速度の発散divv）をもとめる。
    type(field__fluid_t),          intent(in)  :: fluid  !! 流体基本場
    type(field__vector3d_t),       intent(out) :: vel    !! 流れ場
    real(DR), dimension(NX,NY,NZ), intent(out) :: tm     !! 温度場
    real(DR), dimension(NX,NY,NZ), intent(out) :: divv   !! 流れの発散
![   vel = fluid%flux     / fluid%density ! operator defined in field.f90.
     vel = operator_vector_divby_scalar(fluid%flux, fluid%density)
      tm = fluid%pressure / fluid%density
![  divv = .div.vel
    divv = operator_div(vel)
       ! Fortranコンパイラが自己定義演算子（field.f90で定義）
       ! を許せば上の簡潔な記述を使うべし。
    call debug__print("called solver/subfield_vel_tm_divv.")
  end subroutine subfield_vel_tm_divv
Call graph
subfield_vel_tm_divv calls debug__print, operator_vector_divby_scalar, operator_div
debug__print calls print_str_sint, print_str_dint, print_str_double, print_str, print_str_dint_double, print_str_sint_double
operator_div calls boundary_condition_scalar
print_str_sint calls params__get_logical
print_str_dint calls params__get_logical
print_str_double calls ut__message, params__get_logical
print_str calls ut__message, params__get_logical
print_str_dint_double calls params__get_logical
print_str_sint_double calls params__get_logical
ut__message calls message_str_double, message_str_dint_double, message_str_float, message_decorated_str_dint, message_decorated_str, message_str_sint, message_str, message_str_sint_double_double, message_str_dint, message_str_dint_double_double, message_str_sint_double, message_decorated_str_sint
params__get_logical calls ut__message, ut__assert, ut__fatal
ut__assert calls ut__fatal
message_decorated_str_dint calls message_decorated_str
message_decorated_str_sint calls message_decorated_str
ut__fatal calls ut__message
solver__advance calls subfield_vel_tm_divv
solver__get_subfield calls subfield_vel_tm_divv
main_m calls solver__advance, slicedata__write
slicedata__write calls solver__get_subfield