the_equation – Smoke Ring
the_equation Function
45 statements
Source File
private function the_equation(t, dt, vx, vy, vz, tm, divv, fx, fy, fz, ps)
ナビエ・ストークス方程式の右辺（時間変化量）dtを掛けたものを計算
Note
粘性による加熱の効果は小さいので無視している。 この項を入れる場合は圧力の方程式 the_equation%pressure に追加すればよい。
Arguments
Type Intent Optional Attributes Name
real(kind=DR), intent(in) :: t
時刻と時間刻み幅
real(kind=DR), intent(in) :: dt
時刻と時間刻み幅
real(kind=DR), intent(in), dimension(NX,NY,NZ) :: vx
速度3成分
real(kind=DR), intent(in), dimension(NX,NY,NZ) :: vy
速度3成分
real(kind=DR), intent(in), dimension(NX,NY,NZ) :: vz
速度3成分
real(kind=DR), intent(in), dimension(NX,NY,NZ) :: tm
温度と速度の発散
real(kind=DR), intent(in), dimension(NX,NY,NZ) :: divv
温度と速度の発散
real(kind=DR), intent(in), dimension(NX,NY,NZ) :: fx
質量フラックス
real(kind=DR), intent(in), dimension(NX,NY,NZ) :: fy
質量フラックス
real(kind=DR), intent(in), dimension(NX,NY,NZ) :: fz
質量フラックス
real(kind=DR), intent(in), dimension(NX,NY,NZ) :: ps
圧力
Return Value type(field__fluid_t)
時間刻みdtでの流体データの微小変化量
Calls
Called by
Contents
Source Code
the_equation
Source Code
  function the_equation(t,dt,vx,vy,vz,tm,divv,fx,fy,fz,ps)
    !! ナビエ・ストークス方程式の右辺（時間変化量）dtを掛けたものを計算
    !!
    !! @note
    !!    粘性による加熱の効果は小さいので無視している。
    !!    この項を入れる場合は圧力の方程式
    !!    the_equation%pressure に追加すればよい。
    real(DR),                      intent(in) :: t, dt      !! 時刻と時間刻み幅
    real(DR), dimension(NX,NY,NZ), intent(in) :: vx, vy, vz !! 速度3成分
    real(DR), dimension(NX,NY,NZ), intent(in) :: tm, divv   !! 温度と速度の発散
    real(DR), dimension(NX,NY,NZ), intent(in) :: fx, fy, fz !! 質量フラックス
    real(DR), dimension(NX,NY,NZ), intent(in) :: ps         !! 圧力
    type(field__fluid_t) :: the_equation  !! 時間刻みdtでの流体データの微小変化量
    integer(SI) :: i, j, k
    real(DR), parameter :: ONE_THIRD = 1.0_DR / 3.0_DR  ! 演算回数節約のため
    real(DR) :: gradpx, gradpy, gradpz     ! 圧力の勾配 (gradient p)
    real(DR) :: gdivvx, gdivvy, gdivvz     ! 速度の発散の勾配
    real(DR) :: divfvx, divfvy, divfvz     ! 速度・密度フラックステンソルの発散
    real(DR) :: lapvx, lapvy, lapvz, laptm ! 速度と温度のラプラシアン
    real(DR) :: divf                       ! 質量フラックスの発散
    real(DR) :: factor                     ! 渦輪駆動力の係数（時間依存）
    call ut__assert(Initialize_done, "<solver/the_equation> Forgot init?")
      ! 初期化忘れしていないか確認
    factor = drive_force_factor(t)
      ! 渦輪の駆動力はシミュレーション開始直後だけかける。
      ! その後は何も力をかけない（渦輪が自然に発生し、リング上の
      ! 構造が移動していく。）つまりこのfactorはシミュレーション
      ! 開始直後だけ非ゼロで、残りの殆どの時間はゼロが入っている。
    ! 以下のdo loopがこのシミュレーションで最も時間のかかる
    ! 部分である。したがってここでは.div.などのユーザ定義
    ! 演算子は（コンパイラがその使用を許したとしても）あえて
    ! 使わず、泥臭く書いている。これは将来、
    ! 速度向上のためにコードの最適化をしたり、
    ! OpenMP化することを見越してのことである。
    do k = 2 , NZ-1
      do j = 2 , NY-1
        do i = 2 , NX-1
          ! 以下のコメントでは
          ! P 圧力
          ! V 速度場ベクトル
          ! F 質量フラックスベクトル
          ! T 温度
          ! grad P
          gradpx = ( ps(i+1,j,k)-ps(i-1,j,k) ) * grid%d1%x
          gradpy = ( ps(i,j+1,k)-ps(i,j-1,k) ) * grid%d1%y
          gradpz = ( ps(i,j,k+1)-ps(i,j,k-1) ) * grid%d1%z
          ! grad (div V) の3成分
          gdivvx = ( divv(i+1,j,k)-divv(i-1,j,k) ) * grid%d1%x
          gdivvy = ( divv(i,j+1,k)-divv(i,j-1,k) ) * grid%d1%y
          gdivvz = ( divv(i,j,k+1)-divv(i,j,k-1) ) * grid%d1%z
          ! VFテンソルの発散 div(VF) の3成分
          divfvx = ( fx(i+1,j,k)*vx(i+1,j,k)  &
                    -fx(i-1,j,k)*vx(i-1,j,k) ) * grid%d1%x  &
                 + ( fx(i,j+1,k)*vy(i,j+1,k)  &
                    -fx(i,j-1,k)*vy(i,j-1,k) ) * grid%d1%y  &
                 + ( fx(i,j,k+1)*vz(i,j,k+1)  &
                    -fx(i,j,k-1)*vz(i,j,k-1) ) * grid%d1%z
          divfvy = ( fy(i+1,j,k)*vx(i+1,j,k)  &
                    -fy(i-1,j,k)*vx(i-1,j,k) ) * grid%d1%x  &
                 + ( fy(i,j+1,k)*vy(i,j+1,k)  &
                    -fy(i,j-1,k)*vy(i,j-1,k) ) * grid%d1%y  &
                 + ( fy(i,j,k+1)*vz(i,j,k+1)  &
                    -fy(i,j,k-1)*vz(i,j,k-1) ) * grid%d1%z
          divfvz = ( fz(i+1,j,k)*vx(i+1,j,k)  &
                    -fz(i-1,j,k)*vx(i-1,j,k) ) * grid%d1%x  &
                 + ( fz(i,j+1,k)*vy(i,j+1,k)  &
                    -fz(i,j-1,k)*vy(i,j-1,k) ) * grid%d1%y  &
                 + ( fz(i,j,k+1)*vz(i,j,k+1)  &
                    -fz(i,j,k-1)*vz(i,j,k-1) ) * grid%d1%z
          ! Laplacin V の3成分
          lapvx = ( vx(i+1,j,k)-2*vx(i,j,k)+vx(i-1,j,k) )*grid%d2%x &
                + ( vx(i,j+1,k)-2*vx(i,j,k)+vx(i,j-1,k) )*grid%d2%y &
                + ( vx(i,j,k+1)-2*vx(i,j,k)+vx(i,j,k-1) )*grid%d2%z
          lapvy = ( vy(i+1,j,k)-2*vy(i,j,k)+vy(i-1,j,k) )*grid%d2%x &
                + ( vy(i,j+1,k)-2*vy(i,j,k)+vy(i,j-1,k) )*grid%d2%y &
                + ( vy(i,j,k+1)-2*vy(i,j,k)+vy(i,j,k-1) )*grid%d2%z
          lapvz = ( vz(i+1,j,k)-2*vz(i,j,k)+vz(i-1,j,k) )*grid%d2%x &
                + ( vz(i,j+1,k)-2*vz(i,j,k)+vz(i,j-1,k) )*grid%d2%y &
                + ( vz(i,j,k+1)-2*vz(i,j,k)+vz(i,j,k-1) )*grid%d2%z
          ! Laplacin T
          laptm = ( tm(i+1,j,k)-2*tm(i,j,k)+tm(i-1,j,k) )*grid%d2%x &
                + ( tm(i,j+1,k)-2*tm(i,j,k)+tm(i,j-1,k) )*grid%d2%y &
                + ( tm(i,j,k+1)-2*tm(i,j,k)+tm(i,j,k-1) )*grid%d2%z
          ! div F
          divf = ( fx(i+1,j,k)-fx(i-1,j,k) ) * grid%d1%x  &
               + ( fy(i,j+1,k)-fy(i,j-1,k) ) * grid%d1%y  &
               + ( fz(i,j,k+1)-fz(i,j,k-1) ) * grid%d1%z
          ! 以下がナビエ・ストークス方程式
          !  密度の時間発展
          the_equation%density(i,j,k) = -divf*dt
          !  質量フラックスの時間発展（3成分）
          the_equation%flux%x(i,j,k) =  &
               ( - divfvx  &
                 - gradpx  &
                 + Drive_force%x(i,j,k)*factor  &
                 + Viscosity * ( lapvx + ONE_THIRD*gdivvx )  &
               ) * dt
          the_equation%flux%y(i,j,k) =  &
               ( - divfvy  &
                 - gradpy  &
                 + Drive_force%y(i,j,k)*factor  &
                 + Viscosity * ( lapvy + ONE_THIRD*gdivvy )  &
               ) * dt
          the_equation%flux%z(i,j,k) =  &
               ( - divfvz  &
                 - gradpz  &
                 + Drive_force%z(i,j,k)*factor  &
                 + Viscosity * ( lapvz + ONE_THIRD*gdivvz )  &
               ) * dt
          !  圧力の時間発展
          the_equation%pressure(i,j,k) =  &
              ( - ( vx(i,j,k)*gradpx  &
                  + vy(i,j,k)*gradpy  &
                  + vz(i,j,k)*gradpz  &
                  )  &
                + Gamma1_kappa * laptm  &
                - GAMMA * ps(i,j,k) * divv(i,j,k)  &
              ) * dt
        end do
      end do
    end do
    call field__boundary_condition(the_equation)
      ! 境界条件の設定（周期境界条件）
      ! 上のdo loopは境界面上の格子点を除いた格子点（シミュレーション
      ! 領域の内部の格子点）上での値を計算するものであった。
      ! ここで境界面上の格子点の値の（更新されたばかりの）内部の
      ! 格子点上のデータをコピーすることで設定する。
    call debug__print("called solver/the_equation.")
      ! デバッグモードがonの時には毎回メッセージを標準出力に
      ! 書き出す。コードが完成し、product runの段階に入ったら
      ! デバッグモードをoffにすれば、書き出しは抑制される。
      ! この行をコメントアウトする必要はない。
  end function the_equation
Call graph
the_equation calls field__boundary_condition, ut__assert, drive_force_factor, debug__print
field__boundary_condition calls boundary_condition_scalar, boundary_condition_vector, boundary_condition_fluid
ut__assert calls ut__fatal
drive_force_factor calls ut__assert
debug__print calls print_str_sint, print_str_dint, print_str_double, print_str, print_str_dint_double, print_str_sint_double
print_str_sint calls params__get_logical
print_str_dint calls params__get_logical
print_str_double calls ut__message, params__get_logical
print_str calls ut__message, params__get_logical
print_str_dint_double calls params__get_logical
boundary_condition_fluid calls boundary_condition_scalar, boundary_condition_vector
print_str_sint_double calls params__get_logical
ut__fatal calls ut__message
ut__message calls message_str_double, message_str_dint_double, message_str_float, message_decorated_str_dint, message_decorated_str, message_str_sint, message_str, message_str_sint_double_double, message_str_dint, message_str_dint_double_double, message_str_sint_double, message_decorated_str_sint
params__get_logical calls ut__assert, ut__fatal, ut__message
message_decorated_str_dint calls message_decorated_str
message_decorated_str_sint calls message_decorated_str
solver__advance calls the_equation
main_m calls solver__advance