ut__assert – Smoke Ring
ut__assert Subroutine
7 statements
Source File
public subroutine ut__assert(condition, last_will)
アサーション
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: condition
必須条件
character(len=*), intent(in) :: last_will
遺言
Calls
Called by
Contents
Source Code
ut__assert
Source Code
  subroutine ut__assert(condition, last_will)
    !! アサーション
    logical, intent(in)          :: condition !! 必須条件
    character(len=*), intent(in) :: last_will !! 遺言
    if (.not.condition) then
       call ut__fatal(last_will)
    end if
  end subroutine ut__assert
Call graph
ut__assert calls ut__fatal
ut__fatal calls ut__message
ut__message calls message_str_double, message_str_dint_double, message_str_float, message_decorated_str_dint, message_decorated_str, message_str_sint, message_str, message_str_sint_double_double, message_str_dint, message_str_dint_double_double, message_str_sint_double, message_decorated_str_sint
message_decorated_str_dint calls message_decorated_str
message_decorated_str_sint calls message_decorated_str
params__get_string calls ut__assert
the_equation calls ut__assert, drive_force_factor, debug__print
slicedata__write calls ut__assert, params__get_integer, debug__print, make_single_precision_field, solver__get_subfield
params__get_logical calls ut__assert
params__get_double calls ut__assert
drive_force_factor calls ut__assert
solver__set_time_step calls ut__assert, params__get_logical, subfield_vel_tm
params__get_integer calls ut__assert
slicedata__initialize calls params__get_string, debug__print
print_str_sint calls params__get_logical
print_str_dint calls params__get_logical
solver__initialize calls params__get_double, debug__print, set_drive_force_field
print_str_sint_double calls params__get_logical
print_str_double calls params__get_logical
print_str calls params__get_logical
print_str_dint_double calls params__get_logical
solver__advance calls the_equation, debug__print, subfield_vel_tm_divv
main_m calls slicedata__write, solver__set_time_step, params__get_integer, slicedata__initialize, solver__initialize, solver__advance, debug__print, solver__diagnosis
debug__print calls print_str_sint, print_str_dint, print_str_sint_double, print_str_double, print_str, print_str_dint_double
subfield_vel_tm calls debug__print
subfield_vel calls debug__print
set_drive_force_field calls debug__print
make_single_precision_field calls debug__print
subfield_vel_tm_divv calls debug__print
solver__diagnosis calls debug__print, subfield_vel
solver__get_subfield calls subfield_vel_tm, subfield_vel, subfield_vel_tm_divv