ut__fatal – Smoke Ring
ut__fatal Subroutine
5 statements
Source File
public subroutine ut__fatal(last_will)
致命的エラー
遺言を書き出してプログラムを停止する
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: last_will
Calls
Called by
Contents
Source Code
ut__fatal
Source Code
  subroutine ut__fatal(last_will)
    !! 致命的エラー
    !!
    !!   遺言を書き出してプログラムを停止する
    !!
    character(len=*), intent(in) :: last_will
    call ut__message('!',last_will)
    stop 'Program stopped by ut__fatal.'
  end subroutine ut__fatal
Call graph
ut__fatal calls ut__message
ut__message calls message_str_double, message_str_dint_double, message_str_float, message_decorated_str_dint, message_decorated_str, message_str_sint, message_str, message_str_sint_double_double, message_str_dint, message_str_dint_double_double, message_str_sint_double, message_decorated_str_sint
message_decorated_str_dint calls message_decorated_str
message_decorated_str_sint calls message_decorated_str
params__get_string calls ut__fatal, ut__assert
ut__assert calls ut__fatal
params__get_logical calls ut__fatal, ut__assert
params__get_double calls ut__fatal, ut__assert
job__karte_set calls ut__fatal
params__get_integer calls ut__fatal, ut__assert
slicedata__initialize calls params__get_string, debug__print
the_equation calls ut__assert, drive_force_factor, debug__print
slicedata__write calls ut__assert, params__get_integer, debug__print, make_single_precision_field, solver__get_subfield
print_str_sint calls params__get_logical
print_str_dint calls params__get_logical
solver__initialize calls params__get_double, debug__print, set_drive_force_field
print_str_double calls params__get_logical
solver__set_time_step calls ut__assert, params__get_logical, subfield_vel_tm
print_str calls params__get_logical
print_str_dint_double calls params__get_logical
print_str_sint_double calls params__get_logical
main_m calls params__get_integer, slicedata__initialize, slicedata__write, solver__initialize, solver__set_time_step, solver__advance, debug__print, solver__diagnosis
drive_force_factor calls ut__assert
solver__advance calls the_equation, debug__print, subfield_vel_tm_divv
debug__print calls print_str_sint, print_str_dint, print_str_double, print_str, print_str_dint_double, print_str_sint_double
subfield_vel_tm calls debug__print
subfield_vel calls debug__print
set_drive_force_field calls debug__print
make_single_precision_field calls debug__print
subfield_vel_tm_divv calls debug__print
solver__diagnosis calls debug__print, subfield_vel
solver__get_subfield calls subfield_vel_tm, subfield_vel, subfield_vel_tm_divv