vec_amp_max_string – Smoke Ring
vec_amp_max_string Function
7 statements
Source File
private function vec_amp_max_string(vmax) result(string)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: vmax
Return Value character(len=TAG_NAME_MAX)
Calls
Called by
Contents
Source Code
vec_amp_max_string
Source Code
  function vec_amp_max_string( vmax ) result(string)
    real, intent(in) :: vmax
    character(len=TAG_NAME_MAX) :: string
    character(len=10) :: str10_vmax
    str10_vmax = ut__real_to_str10( vmax )
    string = 'vmax = ' // str10_vmax
  end function vec_amp_max_string
Call graph
vec_amp_max_string calls ut__real_to_str10
draw_arrows calls vec_amp_max_string
draw_contour_and_arrows calls vec_amp_max_string
vis2d_plane_xy__draw calls draw_contour_and_arrows
vis2d_plane_xz__draw calls draw_contour_and_arrows