vis2d__draw – Smoke Ring
vis2d__draw Subroutine
20 statements
Source File
public subroutine vis2d__draw(vis2d, t_double, nloop, fluid)
Type Bound
vis2d_t
Arguments
Type Intent Optional Attributes Name
class(vis2d_t), intent(inout) :: vis2d
real(kind=DR), intent(in) :: t_double
integer, intent(in) :: nloop
type(fluid_t), intent(in) :: fluid
Calls
Contents
Source Code
vis2d__draw
Source Code
  subroutine vis2d__draw( vis2d, t_double, nloop, fluid )
    class(vis2d_t), intent(inout) :: vis2d
    real(DR)      , intent(in) :: t_double
    integer       , intent(in) :: nloop
    type(fluid_t) , intent(in) :: fluid
    real :: t
    integer :: ctr = 0
    t = real(t_double,SR)
                                                 call kutimer__start('vis2  ')
    if(mod(ctr,100)==0) then
      call vis2d%set_data( fluid )              !{vis2  }{set d}
      if ( Parallel%rank%me == 0 ) then
        call vis2d%z_upper%draw ( t, nloop )
        call vis2d%z_middle%draw( t, nloop )    !{vis2  }{   xy}
!       call vis2d.z_lower.draw (t, nloop)
!       call vis2d.y_upper.draw (t, nloop)
!       call vis2d.y_middle.draw(t, nloop)
!       call vis2d.y_lower.draw (t, nloop)    !{vis2  }{   xz}
      end if
      call mpiut__barrier( Parallel%comm )
    end if; ctr = ctr + 1
                                                 call kutimer__end('vis2  ')
  end subroutine vis2d__draw
Call graph
vis2d__draw calls kutimer__end, kutimer__start, mpiut__barrier, set_data