vis2d_plane_xz__draw – Smoke Ring
vis2d_plane_xz__draw Subroutine
21 statements
Source File
private subroutine vis2d_plane_xz__draw(plane, t, step)
<
<
Type Bound
vis2d_plane_xz_t
Arguments
Type Intent Optional Attributes Name
class(vis2d_plane_xz_t), intent(inout) :: plane
real, intent(in) :: t
integer, intent(in) :: step
Calls
Contents
Source Code
vis2d_plane_xz__draw
Source Code
  subroutine vis2d_plane_xz__draw( plane, t, step )
    class(vis2d_plane_xz_t), intent(inout) :: plane
    real   , intent(in) :: t
    integer, intent(in) :: step
    character(len=TAG_NAME_MAX) :: tas ! time and step string
    character(len=FILE_NAME_MAX) :: filename
    type(vv_sketch__sim_pos_t) :: ll,  &  ! lower left
                                  ur      ! upper right
    ll%u = XMIN
    ll%v = ZMIN
    ur%u = XMAX
    ur%v = ZMAX
                                               call kutimer__start('vis2xz')
    call make_time_and_step_string( t, step, tas )
!!>
!    call make_filename(tas, plane.tag, plane.pressure.tag, filename)
!    call draw_contour(ll, ur, filename, plane.pressure)
!                                               call kutimer__('vis2xz','  pres')
!    call make_filename(tas, plane.tag, plane.flow_helicity.tag, filename)
!    call draw_contour(ll, ur, filename, plane.flow_helicity)
!                                               call kutimer__('vis2xz','f heli')
!    call make_filename(tas, plane.tag, plane.velocity_y.tag, filename)
!    call draw_contour(ll, ur, filename, plane.velocity_y)
!                                               call kutimer__('vis2xz',' vel z')
!!<
    call make_filename( tas, plane%tag, plane%enstrophy%tag, filename )
    call draw_contour( ll, ur, filename, plane%enstrophy )
                                               call kutimer__('vis2xz','   ens')
!!>
!    call make_filename(tas, plane.tag, plane.velocity.tag, filename)
!    call draw_arrows(ll, ur, filename, plane.velocity)
!                                               call kutimer__('vis2xz','   vel')
!    call make_filename(tas, plane.tag, plane.vorticity.tag, filename)
!    call draw_arrows(ll, ur, filename, plane.vorticity)
!                                               call kutimer__('vis2xz','   vor')
!!<
    call make_filename( tas, plane%tag, 'combined_ens_vel', filename )
    call draw_contour_and_arrows( ll, ur, filename, plane%enstrophy, &
                                                    plane%velocity )
                                               call kutimer__('vis2xz','ensvel')
                                               call kutimer__end('vis2xz')
  end subroutine vis2d_plane_xz__draw
Call graph
vis2d_plane_xz__draw calls kutimer__, kutimer__end, kutimer__start, draw_contour, draw_contour_and_arrows, make_filename, make_time_and_step_string
draw_contour calls finalize, group_pop, group_push, initialize, min_max_string, vis_contour, vv_color__normalized_real_to_color
draw_contour_and_arrows calls comp_u, comp_v, finalize, group_pop, group_push, initialize, min_max_string, vec_amp_max_string, vis_arrows, vis_contour, vv_color__normalized_real_to_color
make_time_and_step_string calls ut__assert, ut__int_to_str8, ut__real_to_str10
min_max_string calls ut__real_to_str10
vec_amp_max_string calls ut__real_to_str10