vis2d_plane_xy__draw – Smoke Ring
vis2d_plane_xy__draw Subroutine
18 statements
Source File
private subroutine vis2d_plane_xy__draw(plane, t, step)
<
Type Bound
vis2d_plane_xy_t
Arguments
Type Intent Optional Attributes Name
class(vis2d_plane_xy_t), intent(inout) :: plane
real, intent(in) :: t
integer, intent(in) :: step
Calls
Contents
Source Code
vis2d_plane_xy__draw
Source Code
  subroutine vis2d_plane_xy__draw( plane, t, step )
    class(vis2d_plane_xy_t), intent(inout) :: plane
    real   , intent(in) :: t
    integer, intent(in) :: step
    character(len=TAG_NAME_MAX) :: tas
    character(len=FILE_NAME_MAX) :: filename
    type(vv_sketch__sim_pos_t) :: ll,  &  ! lower left
                                  ur      ! upper right
    ll%u = XMIN
    ll%v = YMIN
    ur%u = XMAX
    ur%v = YMAX
                                               call kutimer__start('vis2xy')
    call make_time_and_step_string( t, step, tas )
!!>
!    call make_filename(tas, plane.tag, plane.pressure.tag, filename)
!    call draw_contour(ll, ur, filename, plane.pressure)
!                                               call kutimer__('vis2xy','  pres')
!    call make_filename(tas, plane.tag, plane.flow_helicity.tag, filename)
!    call draw_contour(ll, ur, filename, plane.flow_helicity)
!                                               call kutimer__('vis2xy','f heli')
!    call make_filename(tas, plane.tag, plane.velocity_z.tag, filename)
!    call draw_contour(ll, ur, filename, plane.velocity_z)
!                                               call kutimer__('vis2xy',' vel z')
!    call make_filename(tas, plane.tag, plane.enstrophy.tag, filename)
!    call draw_contour(ll, ur, filename, plane.enstrophy)
!                                               call kutimer__('vis2xy','   ens')
!    call make_filename(tas, plane.tag, plane.velocity.tag, filename)
!    call draw_arrows(ll, ur, filename, plane.velocity)
!                                               call kutimer__('vis2xy','   vel')
!    call make_filename(tas, plane.tag, plane.vorticity.tag, filename)
!    call draw_arrows(ll, ur, filename, plane.vorticity)
!                                               call kutimer__('vis2xy','   vor')
!!<
    call make_filename( tas, plane%tag, 'enstrophy_and_flow', filename )
    call draw_contour_and_arrows( ll, ur, filename, plane%enstrophy,  &
                                                    plane%velocity  )
                                               call kutimer__('vis2xy','ensvel')
                                               call kutimer__end('vis2xy')
  end subroutine vis2d_plane_xy__draw
Call graph
vis2d_plane_xy__draw calls kutimer__, kutimer__end, kutimer__start, draw_contour_and_arrows, make_filename, make_time_and_step_string
draw_contour_and_arrows calls comp_u, comp_v, finalize, group_pop, group_push, initialize, min_max_string, vec_amp_max_string, vis_arrows, vis_contour, vv_color__normalized_real_to_color
make_time_and_step_string calls ut__assert, ut__int_to_str8, ut__real_to_str10
min_max_string calls ut__real_to_str10
vec_amp_max_string calls ut__real_to_str10