#!/bin/bash
#-------------------------------------------------------------------
# class-hpc-smoke-ring: A simple sample field solver.
#
#    by Akira Kageyama, Kobe University, Japan.
#       email: sgks@mac.com
#
#    Copyright 2018 Akira Kageyama
#
#    This software is released under the MIT License.
#
#-------------------------------------------------------------------
#    src/make_plotscript.sh
#-------------------------------------------------------------------
#

function count_keta() {
  #
  # called from pad_zero()
  #
  i=$1 # integer to be counted
  keta=0
  while [ $i -gt 0 ]
  do
    i=$((i/10))
    ((keta++))
  done
  echo $keta
}

function pad_zero() {
  # zero padding for an integer
  #
  # when total_keta=7
  #      6 ==> 0000006
  #     56 ==> 0000056
  #    456 ==> 0000456
  #   3456 ==> 0003456
  #  23456 ==> 0023456
  # 123456 ==> 0123456
  #
  input_integer=$1
  keta_total=10
  keta_input_integer=`count_keta $input_integer`
  num_of_zeros=$((keta_total-keta_input_integer))

  for i in `seq 1 $num_of_zeros`
  do
    echo -n '0'
  done
  echo $input_integer
}

if [ $# -eq 0 ]
then
  echo '*** Usage: make_plotscript.sh nloop'
  exit
fi

nloop=`pad_zero $1`

echo $nloop | ./gnuplot_data_generator

for i in `ls Workfiles/*.tt`
do
  size=`ls -l $i | awk '{print $5}'` >> /dev/null
  if [ $size -eq 0 ]
  then
    echo '0.0 0.0' >> $i   # Dummy data
  fi
done

cat > Workfiles/plot.gp <<EOF
# turtle.gp
#   - A gnuplot script
#   - Automatically generated by make_plotscript.sh

set xrange [-1.8:1.8]
set yrange [-0.8:0.8]

# set size 0.75, 1.0
set size 1.0, 1.0

set label "nloop = $nloop" at -1.5, 0.75

# set terminal aqua

set terminal postscript eps color solid

set output "Workfiles/fig.zxplane.${nloop}.eps"

plot	"Workfiles/lines.boundary_box.tt"	w l lt 1 title "",	    \
 	"Workfiles/lines.zxplane_contour_en.tt"	w l lt 3 title "Enstrophy", \
 	"Workfiles/lines.zxplane_vector_vel.tt"	w l lt 4 title "(Vx,Vy)"
EOF

