#!/bin/sh
#-------------------------------------------------------------------
# class-hpc-smoke-ring: A simple sample field solver.
#
#    by Akira Kageyama, Kobe University, Japan.
#       email: sgks@mac.com
#
#    Copyright 2018 Akira Kageyama
#
#    This software is released under the MIT License.
#
#-------------------------------------------------------------------
#    src/make_plotscript.sh
#-------------------------------------------------------------------
#

function zeropad () {
  #      6 ==> 000006
  #     56 ==> 000056
  #    456 ==> 000456
  #   3456 ==> 003456
  #  23456 ==> 023456
  # 123456 ==> 123456

  if [ $1 -lt 10 ]
  then
    echo 00000$1
  elif [ $1 -lt 100 ]
  then
    echo 0000$1
  elif [ $1 -lt 1000 ]
  then
    echo 000$1
  elif [ $1 -lt 10000 ]
  then
    echo 00$1
  elif [ $1 -lt 100000 ]
  then
    echo 0$1
  else
    echo $1
  fi
}

if [ $# -eq 0 ]
then
  echo '*** Usage: make_plotscript.sh nloop'
  exit
fi

nloop=`zeropad $1`

echo $nloop | ./gnuplot_data_generator

for i in `ls Workfiles/*.tt`
do
  size=`ls -l $i | awk '{print $5}'` >> /dev/null
  if [ $size -eq 0 ]
  then
    echo '0.0 0.0' >> $i   # Dummy data
  fi
done

cat > Workfiles/plot.gp <<EOF
# turtle.gp
#   - A gnuplot script
#   - Automatically generated by make_plotscript.sh

set xrange [-1.8:1.8]
set yrange [-0.8:0.8]

# set size 0.75, 1.0
set size 1.0, 1.0

set label "nloop = $nloop" at -1.5, 0.75

# set terminal aqua

set terminal postscript eps color solid

set output "Workfiles/fig.zxplane.${nloop}.eps"

plot	"Workfiles/lines.boundary_box.tt"	w l lt 1 title "",	    \
 	"Workfiles/lines.zxplane_contour_en.tt"	w l lt 3 title "Enstrophy", \
 	"Workfiles/lines.zxplane_vector_vel.tt"	w l lt 4 title "(Vx,Vy)"
EOF

