debug__print – Smoke Ring
debug__print Interface
3 statements
Source File
public interface debug__print
各種デバッグ出力の多重定義
Calls
Called by
Contents
Module Procedures
print_str print_str_dint print_str_dint_double print_str_double print_str_sint print_str_sint_double
Module Procedures
private subroutine print_str(string)
Debugパラメータがtrueのとき文字列を出力する
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
出力文字列
private subroutine print_str_dint(string, int)
Debugパラメータがtrueのとき文字列と整数を出力する
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
出力文字列
integer(kind=DI), intent(in) :: int
出力整数
private subroutine print_str_dint_double(string, i1, d1)
Debugパラメータがtrueのとき文字列と整数と実数を出力する
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
出力文字列
integer(kind=DI), intent(in) :: i1
出力整数
real(kind=DR), intent(in) :: d1
出力実数
private subroutine print_str_double(string, double)
Debugパラメータがtrueのとき文字列と実数を出力する
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
出力文字列
real(kind=DR), intent(in) :: double
出力実数
private subroutine print_str_sint(string, int)
Debugパラメータがtrueのとき文字列と整数を出力する
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
出力文字列
integer(kind=SI), intent(in) :: int
出力整数
private subroutine print_str_sint_double(string, i1, d1)
Debugパラメータがtrueのとき文字列と整数と実数を出力する
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
出力文字列
integer(kind=SI), intent(in) :: i1
出力整数
real(kind=DR), intent(in) :: d1
出力実数
Call graph
debug__print calls print_str_sint, print_str_dint, print_str_double, print_str, print_str_dint_double, print_str_sint_double
print_str_sint calls params__get_logical
print_str_dint calls params__get_logical
print_str_double calls ut__message, params__get_logical
print_str calls ut__message, params__get_logical
print_str_dint_double calls params__get_logical
print_str_sint_double calls params__get_logical
ut__message calls message_str_double, message_str_dint_double, message_str_float, message_decorated_str_dint, message_decorated_str, message_str_sint, message_str, message_str_sint_double_double, message_str_dint, message_str_dint_double_double, message_str_sint_double, message_decorated_str_sint
params__get_logical calls ut__message, ut__assert, ut__fatal
ut__assert calls ut__fatal
message_decorated_str_dint calls message_decorated_str
message_decorated_str_sint calls message_decorated_str
ut__fatal calls ut__message
slicedata__initialize calls debug__print
the_equation calls debug__print
subfield_vel_tm calls debug__print
slicedata__write calls debug__print, make_single_precision_field, solver__get_subfield
solver__initialize calls debug__print, set_drive_force_field
subfield_vel calls debug__print
set_drive_force_field calls debug__print
subfield_vel_tm_divv calls debug__print
make_single_precision_field calls debug__print
solver__advance calls debug__print, the_equation, subfield_vel_tm_divv
main_m calls debug__print, slicedata__initialize, slicedata__write, solver__initialize, solver__advance, solver__diagnosis, solver__set_time_step
solver__diagnosis calls debug__print, subfield_vel
solver__get_subfield calls subfield_vel_tm, subfield_vel, subfield_vel_tm_divv
solver__set_time_step calls subfield_vel_tm