field__boundary_condition – Smoke Ring
field__boundary_condition Interface
3 statements
Source File
public interface field__boundary_condition
境界条件呼び出しルーチンの多重定義 境界条件を設定する変数の種類によって 実際に使用するルーチンが違うが、 呼び出し側では統一した名前でcallする。 コンパイラは引数の型で使用するルーチンを 判断する。
Calls
Called by
Contents
Module Procedures
boundary_condition_scalar boundary_condition_vector
Module Procedures
private subroutine boundary_condition_scalar(scalar)
スカラー場の境界条件設定 プロセス間通信で領域境界データを交換
Arguments
Type Intent Optional Attributes Name
real(kind=DR), intent(inout), dimension(0:NXPP1,0:NYPP1,0:NZPP1) :: scalar
スカラー場
Read more…
private subroutine boundary_condition_vector(vector)
ベクトル場の境界条件設定 プロセス間通信で領域境界データを交換
Arguments
Type Intent Optional Attributes Name
type(field__vector_t), intent(inout) :: vector
ベクトル場
Read more…
Call graph
field__boundary_condition calls boundary_condition_scalar, boundary_condition_vector
boundary_condition_scalar calls mpiut__barrier, mpiut__exchange
boundary_condition_vector calls mpiut__barrier, mpiut__exchange
operator_curl calls field__boundary_condition
operator_div calls field__boundary_condition
operator_laplacian_scalar calls field__boundary_condition
operator_laplacian_vector calls field__boundary_condition
set_drive_force_field calls field__boundary_condition
operator( .curl. ) calls operator_curl
operator( .div. ) calls operator_div
operator( .laplacian. ) calls operator_laplacian_scalar, operator_laplacian_vector
solver__initialize calls set_drive_force_field