operator( .laplacian. ) – Smoke Ring
operator(.laplacian.) Interface
4 statements
Source File
public interface operator(.laplacian.)
ラプラシアン演算子 スカラー場とベクトル場用の2つの多重定義
Calls
Contents
Module Procedures
operator_laplacian_scalar operator_laplacian_vector
Module Procedures
private function operator_laplacian_scalar(a)
スカラー場のラプラシアン
Arguments
Type Intent Optional Attributes Name
real(kind=DR), intent(in), dimension(0:NXPP1,0:NYPP1,0:NZPP1) :: a
入力スカラー場
Return Value real(kind=DR), dimension(0:NXPP1,0:NYPP1,0:NZPP1)
計算結果
private function operator_laplacian_vector(a)
ベクトル場のラプラシアン
Arguments
Type Intent Optional Attributes Name
type(field__vector_t), intent(in) :: a
入力ベクトル場
Return Value type(field__vector_t)
計算結果
Call graph
operator( .laplacian. ) calls operator_laplacian_scalar, operator_laplacian_vector
operator_laplacian_scalar calls field__boundary_condition
operator_laplacian_vector calls field__boundary_condition, x, y, z
field__boundary_condition calls boundary_condition_scalar, boundary_condition_vector
boundary_condition_scalar calls mpiut__barrier, mpiut__exchange
boundary_condition_vector calls mpiut__barrier, mpiut__exchange