operator( * ) – Smoke Ring
operator(*) Interface
6 statements
Source File
public interface operator(*)
各種構造体に掛け算記号が使えるように定義
Calls
Contents
Module Procedures
operator_real_times_vector operator_scalar_times_vector operator_vector_times_real operator_vector_times_scalar
Module Procedures
private function operator_real_times_vector(real, vec)
実数にベクトル場を掛ける演算子
Arguments
Type Intent Optional Attributes Name
real(kind=DR), intent(in) :: real
掛ける実数
type(field__vector_t), intent(in) :: vec
流体場
Return Value type(field__vector_t)
計算結果
private function operator_scalar_times_vector(scalar, vec)
スカラー場にベクトル場を掛ける演算子
Arguments
Type Intent Optional Attributes Name
real(kind=DR), intent(in), dimension(0:NXPP1,0:NYPP1,0:NZPP1) :: scalar
スカラー場
type(field__vector_t), intent(in) :: vec
ベクトル場
Return Value type(field__vector_t)
計算結果
private function operator_vector_times_real(vec, real)
ベクトル場の実数倍の演算子
Arguments
Type Intent Optional Attributes Name
type(field__vector_t), intent(in) :: vec
ベクトル場
real(kind=DR), intent(in) :: real
掛ける実数
Return Value type(field__vector_t)
計算結果
private function operator_vector_times_scalar(vec, scalar)
ベクトル場にスカラー場を掛ける
Arguments
Type Intent Optional Attributes Name
type(field__vector_t), intent(in) :: vec
ベクトル場
real(kind=DR), intent(in), dimension(0:NXPP1,0:NYPP1,0:NZPP1) :: scalar
スカラー場
Return Value type(field__vector_t)
計算結果
Call graph
operator( ASTERISK ) calls operator_real_times_vector, operator_scalar_times_vector, operator_vector_times_real, operator_vector_times_scalar