solver__get_subfield – Smoke Ring
solver__get_subfield Interface
3 statements
Source File
public interface solver__get_subfield
流体の基本変数（質量フラックス、質量密度、圧力） から二次的な量（流れ場、温度場、速度の発散） を計算するためのルーチン群の多重定義
Calls
Called by
Contents
Module Procedures
subfield_vel subfield_vel_tm subfield_vel_tm_divv
Module Procedures
private subroutine subfield_vel(fluid, vel)
fluidの基本変数から二次的な場vel（流れの速度ベクトル場） をもとめる。
Arguments
Type Intent Optional Attributes Name
type(field__fluid_t), intent(in) :: fluid
流体基本場
type(field__vector3d_t), intent(out) :: vel
流れの速度ベクトル
private subroutine subfield_vel_tm(fluid, vel, tm)
fluidの基本変数から二次的な場（速度ベクトル場velと温度場tm） をもとめる。
Arguments
Type Intent Optional Attributes Name
type(field__fluid_t), intent(in) :: fluid
流体基本場
type(field__vector3d_t), intent(out) :: vel
流れ場
real(kind=DR), intent(out), dimension(NX,NY,NZ) :: tm
温度場
private subroutine subfield_vel_tm_divv(fluid, vel, tm, divv)
fluidの基本変数から二次的な場（速度ベクトル場velと 温度場tmと速度の発散divv）をもとめる。
Arguments
Type Intent Optional Attributes Name
type(field__fluid_t), intent(in) :: fluid
流体基本場
type(field__vector3d_t), intent(out) :: vel
流れ場
real(kind=DR), intent(out), dimension(NX,NY,NZ) :: tm
温度場
real(kind=DR), intent(out), dimension(NX,NY,NZ) :: divv
流れの発散
Call graph
solver__get_subfield calls subfield_vel, subfield_vel_tm_divv, subfield_vel_tm
subfield_vel calls debug__print, operator_vector_divby_scalar
subfield_vel_tm_divv calls debug__print, operator_vector_divby_scalar, operator_div
subfield_vel_tm calls debug__print, operator_vector_divby_scalar
debug__print calls print_str_sint, print_str_dint, print_str_double, print_str, print_str_dint_double, print_str_sint_double
operator_div calls boundary_condition_scalar
print_str_sint calls params__get_logical
print_str_dint calls params__get_logical
print_str_double calls ut__message, params__get_logical
print_str calls ut__message, params__get_logical
print_str_dint_double calls params__get_logical
print_str_sint_double calls params__get_logical
ut__message calls message_str_double, message_str_dint_double, message_str_float, message_decorated_str_dint, message_decorated_str, message_str_sint, message_str, message_str_sint_double_double, message_str_dint, message_str_dint_double_double, message_str_sint_double, message_decorated_str_sint
params__get_logical calls ut__message, ut__assert, ut__fatal
ut__assert calls ut__fatal
message_decorated_str_dint calls message_decorated_str
message_decorated_str_sint calls message_decorated_str
ut__fatal calls ut__message
slicedata__write calls solver__get_subfield
main_m calls slicedata__write