ut__message – Smoke Ring
ut__message Interface
3 statements
Source File
public interface ut__message
文字列（+ 数値）を標準出力に書き出すルーチンの多重定義
message_decorated_なんとか は飾り文字で囲む
message_型名[_型名] は文字列の後のその型の数値を同じ行に書く
Calls
Called by
Contents
Module Procedures
message_decorated_str message_decorated_str_dint message_decorated_str_sint message_str message_str_double message_str_float message_str_dint message_str_dint_double message_str_dint_double_double message_str_sint message_str_sint_double message_str_sint_double_double
Module Procedures
private subroutine message_decorated_str(mark, string)
飾り文字でメーセージ文を囲む
Read more…
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: mark
この文字でメーセージを囲む
character(len=*), intent(in) :: string
出力メーセージ（文字列）
private subroutine message_decorated_str_dint(mark, string, int)
飾り文字でメーセージ文と倍精度整数を囲む
Read more…
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: mark
この文字で全体を囲む
character(len=*), intent(in) :: string
メーセージ文字列
integer(kind=DI), intent(in) :: int
文字列の後に書く倍精度整数
private subroutine message_decorated_str_sint(mark, string, int)
飾り文字でメーセージ文と単精度整数を囲む
Read more…
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: mark
この文字で全体を囲む
character(len=*), intent(in) :: string
メーセージ文字列
integer(kind=SI), intent(in) :: int
文字列の後に書く単精度整数
private subroutine message_str(string)
普通のprint文
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
メーセージ文字列
private subroutine message_str_double(string, double)
文字列 + 倍精度実数2つの出力
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
メーセージ文字列
real(kind=DR), intent(in) :: double
書き出される実数
private subroutine message_str_float(string, float)
文字列 + 単精度実数2つの出力
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
メーセージ文字列
real(kind=SR), intent(in) :: float
書き出される実数
private subroutine message_str_dint(string, int)
文字列 + 倍精度整数の出力
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
メーセージ文字列
integer(kind=DI), intent(in) :: int
書き出される整数
private subroutine message_str_dint_double(string, i1, d1)
文字列 + 倍精度整数 + 倍精度実数の出力
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
メーセージ文字列
integer(kind=DI), intent(in) :: i1
書き出される整数
real(kind=DR), intent(in) :: d1
書き出される実数
private subroutine message_str_dint_double_double(string, i1, d1, d2)
文字列 + 倍精度整数 + 倍精度実数 + 倍精度実数の出力
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
メーセージ文字列
integer(kind=DI), intent(in) :: i1
書き出される整数
real(kind=DR), intent(in) :: d1
書き出される実数
real(kind=DR), intent(in) :: d2
書き出される実数
private subroutine message_str_sint(string, int)
文字列 + 単精度整数の出力
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
メーセージ文字列
integer(kind=SI), intent(in) :: int
書き出される整数
private subroutine message_str_sint_double(string, i1, d1)
文字列 + 単精度整数 + 倍精度実数の出力
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
メーセージ文字列
integer(kind=SI), intent(in) :: i1
書き出される整数
real(kind=DR), intent(in) :: d1
書き出される実数
private subroutine message_str_sint_double_double(string, i1, d1, d2)
文字列 + 単精度整数 + 倍精度実数 + 倍精度実数の出力
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
メーセージ文字列
integer(kind=SI), intent(in) :: i1
書き出される整数
real(kind=DR), intent(in) :: d1
書き出される実数
real(kind=DR), intent(in) :: d2
書き出される実数
Call graph
ut__message calls message_str_double, message_str_dint_double, message_str_float, message_decorated_str_dint, message_decorated_str, message_str_sint, message_str, message_str_sint_double_double, message_str_dint, message_str_dint_double_double, message_str_sint_double, message_decorated_str_sint
message_decorated_str_dint calls message_decorated_str
message_decorated_str_sint calls message_decorated_str
params__get_string calls ut__message, ut__fatal, ut__assert
slicedata__write calls ut__message, params__get_integer, debug__print, ut__assert, make_single_precision_field, solver__get_subfield
ut__fatal calls ut__message
print_str_double calls ut__message, params__get_logical
params__get_logical calls ut__message, ut__fatal, ut__assert
print_str calls ut__message, params__get_logical
params__get_double calls ut__message, ut__fatal, ut__assert
job__finalize calls ut__message
solver__set_time_step calls ut__message, params__get_logical, ut__assert, subfield_vel_tm
solver__diagnosis calls ut__message, debug__print, subfield_vel
params__get_integer calls ut__message, ut__fatal, ut__assert
slicedata__initialize calls params__get_string, debug__print
debug__print calls print_str_double, print_str, print_str_sint, print_str_dint, print_str_dint_double, print_str_sint_double
print_str_sint calls params__get_logical
print_str_dint calls params__get_logical
solver__initialize calls params__get_double, debug__print, set_drive_force_field
ut__assert calls ut__fatal
print_str_dint_double calls params__get_logical
job__karte_set calls ut__fatal
print_str_sint_double calls params__get_logical
main_m calls slicedata__write, job__finalize, solver__set_time_step, solver__diagnosis, params__get_integer, slicedata__initialize, debug__print, solver__initialize, solver__advance
the_equation calls debug__print, ut__assert, drive_force_factor
subfield_vel_tm calls debug__print
subfield_vel calls debug__print
set_drive_force_field calls debug__print
subfield_vel_tm_divv calls debug__print
make_single_precision_field calls debug__print
solver__advance calls debug__print, the_equation, subfield_vel_tm_divv
drive_force_factor calls ut__assert
solver__get_subfield calls subfield_vel_tm, subfield_vel, subfield_vel_tm_divv